CREATE TYPE [RA_INTL_SMS].[SMSType] AS TABLE (
    [ID]                     BIGINT           NULL,
    [OperatorID]             BIGINT           NULL,
    [TrafficDirection]       INT              NULL,
    [DataSourceID]           UNIQUEIDENTIFIER NULL,
    [ProbeID]                BIGINT           NULL,
    [IDOnSwitch]             VARCHAR (255)    NULL,
    [SentDateTime]           DATETIME         NULL,
    [DeliveredDateTime]      DATETIME         NULL,
    [Sender]                 VARCHAR (40)     NULL,
    [Receiver]               VARCHAR (40)     NULL,
    [Tag]                    VARCHAR (255)    NULL,
    [OutCarrier]             VARCHAR (40)     NULL,
    [InCarrier]              VARCHAR (40)     NULL,
    [ExtraFields]            NVARCHAR (MAX)   NULL,
    [CustomerDeliveryStatus] VARCHAR (50)     NULL,
    [OriginationMNC]         VARCHAR (20)     NULL,
    [OriginationMCC]         VARCHAR (20)     NULL,
    [DestinationMNC]         VARCHAR (20)     NULL,
    [DestinationMCC]         VARCHAR (20)     NULL,
    [QueueItemId]            BIGINT           NULL);

