CREATE TABLE [CRMFixedOper].[Customer] (
    [ID]                    BIGINT           IDENTITY (1, 1) NOT NULL,
    [CustomerCategoryID]    UNIQUEIDENTIFIER NULL,
    [BillingCustomerID]     NVARCHAR (255)   NULL,
    [BillingCustomerStatus] NVARCHAR (255)   NULL,
    [FileNotes]             NVARCHAR (255)   NULL,
    [RegionID]              INT              NULL,
    [CityID]                INT              NULL,
    [TownID]                INT              NULL,
    [Street]                NVARCHAR (255)   NULL,
    [Building]              NVARCHAR (255)   NULL,
    [FloorNumber]           INT              NULL,
    [AddressNotes]          NVARCHAR (255)   NULL,
    [PhoneNumber]           NVARCHAR (255)   NULL,
    [MobileNumber]          NVARCHAR (255)   NULL,
    [Email]                 NVARCHAR (255)   NULL,
    [FaxNumber]             NVARCHAR (255)   NULL,
    [FirstName]             NVARCHAR (255)   NULL,
    [MiddleName]            NVARCHAR (255)   NULL,
    [LastName]              NVARCHAR (255)   NULL,
    [SalutationID]          UNIQUEIDENTIFIER NULL,
    [CreatedTime]           DATETIME         NULL,
    [CreatedBy]             INT              NULL,
    [LastModifiedTime]      DATETIME         NULL,
    [LastModifiedBy]        INT              NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([ID] ASC)
);

