CREATE TABLE [CRMFixedOper].[Ticket] (
    [ID]               BIGINT           IDENTITY (1, 1) NOT NULL,
    [Case]             BIGINT           NULL,
    [TicketType]       INT              NULL,
    [ReferenceNumber]  NVARCHAR (255)   NULL,
    [Customer]         BIGINT           NULL,
    [Order]            BIGINT           NULL,
    [Title]            NVARCHAR (255)   NULL,
    [AssignedGroup]    INT              NULL,
    [StatusID]         UNIQUEIDENTIFIER NULL,
    [StartedBy]        INT              NULL,
    [CompletedBy]      INT              NULL,
    [StartedTime]      DATETIME         NULL,
    [CompletedTime]    DATETIME         NULL,
    [EscalationLevel]  INT              NULL,
    [CustomFields]     NVARCHAR (MAX)   NULL,
    [TaskId]           BIGINT           NULL,
    [CreatedTime]      DATETIME         NULL,
    [CreatedBy]        INT              NULL,
    [LastModifiedTime] DATETIME         NULL,
    [LastModifiedBy]   INT              NULL,
    [FloorNumber]      INT              NULL,
    [FloorSide]        INT              NULL,
    [Street]           NVARCHAR (255)   NULL,
    [Building]         NVARCHAR (255)   NULL,
    [BuildingSize]     INT              NULL,
    [BlockNumber]      NVARCHAR (255)   NULL,
    [Region]           INT              NULL,
    [City]             INT              NULL,
    [Town]             INT              NULL,
    [FreeNotes]        NVARCHAR (255)   NULL,
    [Attachments]      NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK__Ticket__3214EC2755F4C372] PRIMARY KEY CLUSTERED ([ID] ASC)
);

