CREATE TABLE [CRMFixedOper].[WorkOrder] (
    [ID]                BIGINT           IDENTITY (1, 1) NOT NULL,
    [Title]             NVARCHAR (255)   NULL,
    [ExchangeNumber]    NVARCHAR (255)   NULL,
    [AreaID]            BIGINT           NULL,
    [ReferenceNumber]   NVARCHAR (255)   NULL,
    [StatusID]          UNIQUEIDENTIFIER NULL,
    [AssignedGroupID]   INT              NULL,
    [StartedBy]         INT              NULL,
    [CompletedBy]       INT              NULL,
    [StartedTime]       DATETIME         NULL,
    [CompletedTime]     DATETIME         NULL,
    [EscalationLevel]   INT              NULL,
    [CreatedTime]       DATETIME         NULL,
    [CreatedBy]         INT              NULL,
    [LastModifiedTime]  DATETIME         NULL,
    [LastModifiedBy]    INT              NULL,
    [CustomFields]      NVARCHAR (MAX)   NULL,
    [OrderID]           BIGINT           NULL,
    [WorkOrderTypeID]   UNIQUEIDENTIFIER NULL,
    [WorkOrderGroupID]  UNIQUEIDENTIFIER NULL,
    [TaskID]            BIGINT           NULL,
    [CustomerID]        BIGINT           NULL,
    [WorkOrderActionID] UNIQUEIDENTIFIER NULL,
    [WorkOrderNoteID]   UNIQUEIDENTIFIER NULL,
    [FreeNotes]         NVARCHAR (255)   NULL,
    [Attachments]       NVARCHAR (MAX)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

