CREATE TABLE [Mediation_WHS].[CDR] (
    [Id]                        BIGINT       IDENTITY (1, 1) NOT NULL,
    [SwitchID]                  INT          NULL,
    [RecordType]                INT          NULL,
    [CDPN]                      VARCHAR (20) NULL,
    [CGPN]                      VARCHAR (20) NULL,
    [RecordEntity]              VARCHAR (20) NULL,
    [MSCIncomingRoute]          VARCHAR (20) NULL,
    [MSCOutgoingRoute]          VARCHAR (20) NULL,
    [ConnectDateTime]           DATETIME     NULL,
    [DisconnectDateTime]        DATETIME     NULL,
    [DurationInSeconds]         INT          NULL,
    [Diagnostics]               VARCHAR (20) NULL,
    [HLC]                       VARCHAR (20) NULL,
    [BasicService]              INT          NULL,
    [AdditionalInfoCharge]      INT          NULL,
    [ChangeAreaCode]            INT          NULL,
    [RoamingNumber]             VARCHAR (20) NULL,
    [MSCIncomingCircuit]        VARCHAR (20) NULL,
    [MSCID]                     VARCHAR (20) NULL,
    [CallEmplPriority]          VARCHAR (20) NULL,
    [CUGIndicatorAccess]        VARCHAR (20) NULL,
    [MSCIncomingRouteAttribute] VARCHAR (20) NULL,
    [NetworkCallReference]      VARCHAR (20) NULL,
    [DisconnectParty]           VARCHAR (20) NULL,
    [AudioDataType]             VARCHAR (20) NULL,
    [TranslatedNumber]          VARCHAR (20) NULL,
    [CellId]                    INT          NULL,
    [FirstMSC]                  VARCHAR (20) NULL,
    [LastMSC]                   VARCHAR (20) NULL,
    [RecordNumber]              BIGINT       NULL,
    [CallReference]             BIGINT       NULL,
    [LAC]                       INT          NULL,
    [CauseForTermination]       INT          NULL,
    [AttemptDateTime]           DATETIME     NULL,
    CONSTRAINT [PK_WHS_CDR] PRIMARY KEY CLUSTERED ([Id] ASC)
);

