<?xml version="1.0" encoding="utf-8"?><Database Name="CallGenerator" Class="CallGeneratorModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ScheduleLogs" Member="ScheduleLogs">
    <Type Name="ScheduleLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IsSuccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_ScheduleLog" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleGroups" Member="ScheduleGroups">
    <Type Name="ScheduleGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestNumberGroup_ScheduleGroup" Member="TestNumberGroup" ThisKey="GroupId" OtherKey="Id" Type="TestNumberGroup" IsForeignKey="true" />
      <Association Name="Schedule_ScheduleGroup" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TestNumberGroups" Member="TestNumberGroups">
    <Type Name="TestNumberGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TestNumberGroup_ScheduleGroup" Member="ScheduleGroups" ThisKey="Id" OtherKey="GroupId" Type="ScheduleGroup" />
      <Association Name="TestNumberGroup_TestNumber" Member="TestNumbers" ThisKey="Id" OtherKey="GroupId" Type="TestNumber" />
    </Type>
  </Table>
  <Table Name="dbo.TestNumbers" Member="TestNumbers">
    <Type Name="TestNumber">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TestNumberGroup_TestNumber" Member="TestNumberGroup" ThisKey="GroupId" OtherKey="Id" Type="TestNumberGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ScheduleNumbers">
    <Type Name="ScheduleNumbers">
      <Column Name="Number" Type="System.String" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneratedCalls" Member="GeneratedCalls">
    <Type Name="GeneratedCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartCall" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_GeneratedCall" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="SipAccount_GeneratedCall" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewActionLog" Member="NewActionLogs">
    <Type Name="NewActionLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RemoteAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComputerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewExceptions" Member="NewExceptions">
    <Type Name="NewException">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ExceptionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSuperAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Guid" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IpSwitch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CallerId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WebsiteURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsChangedCallerId" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Schedule" Member="Schedules" ThisKey="Id" OtherKey="UserId" Type="Schedule" />
      <Association Name="User_SipAccount" Member="SipAccounts" ThisKey="Id" OtherKey="UserId" Type="SipAccount" />
    </Type>
  </Table>
  <Table Name="dbo.CDR" Member="CDRs">
    <Type Name="CDR">
      <Column Name="CDRID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDonSwitch" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AttemptDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AlertDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConnectDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DisconnectDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DurationInSeconds" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IN_TRUNK" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IN_CIRCUIT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IN_CARRIER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IN_IP" Type="System.String" DbType="VarChar(21)" CanBeNull="true" />
      <Column Name="OUT_TRUNK" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OUT_CIRCUIT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OUT_CARRIER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OUT_IP" Type="System.String" DbType="VarChar(21)" CanBeNull="true" />
      <Column Name="CGPN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CDPN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CAUSE_FROM_RELEASE_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CAUSE_FROM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CAUSE_TO_RELEASE_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CAUSE_TO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Extra_Fields" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsRerouted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CDPNOut" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SIP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecievedCLI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="CDRHistories">
    <Type Name="CDRHistory">
      <Column Name="ConnectDateTime" Type="System.DateTime" CanBeNull="true" />
      <Column Name="DisconnectDateTime" Type="System.DateTime" CanBeNull="true" />
      <Column Name="CDPN" Type="System.String" CanBeNull="true" />
      <Column Name="CAUSE_FROM_RELEASE_CODE" Type="System.String" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" CanBeNull="true" />
      <Column Name="RowCount" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeFrequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MonthDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OccursEvery" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecificTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TotalNumbers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatioOfCalls" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Schedule_ScheduleLog" Member="ScheduleLogs" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleLog" />
      <Association Name="Schedule_ScheduleGroup" Member="ScheduleGroups" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleGroup" />
      <Association Name="Schedule_GeneratedCall" Member="GeneratedCalls" ThisKey="Id" OtherKey="ScheduleId" Type="GeneratedCall" />
      <Association Name="User_Schedule" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="SipAccount_Schedule" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SipAccounts" Member="SipAccounts">
    <Type Name="SipAccount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Server" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UseProxy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProxyServer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ProxyUser" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ProxyPass" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TotalLines" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseAudio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultAudioFileName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DefaultAudioFile" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PlaybackDevice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NetworkInterface" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Codecs" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SipAccount_GeneratedCall" Member="GeneratedCalls" ThisKey="Id" OtherKey="SipAccountId" Type="GeneratedCall" />
      <Association Name="SipAccount_Schedule" Member="Schedules" ThisKey="Id" OtherKey="SipAccountId" Type="Schedule" />
      <Association Name="User_SipAccount" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ChartCalls">
    <Type Name="ChartCalls">
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="TotalCalls" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetScheduleNumbers" Method="GetScheduleNumbers">
    <Parameter Name="ScheduleId" Parameter="scheduleId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetScheduleNumbersResult">
      <Column Name="Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCDR" Method="GetCDR">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Number" Parameter="number" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="ClientId" Parameter="clientId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayStart" Parameter="displayStart" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayLength" Parameter="displayLength" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCDRResult">
      <Column Name="RowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ConnectDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DisconnectDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CDPN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CAUSE_FROM_RELEASE_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[RowCount]" Member="RowCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetChartTotals" Method="GetChartTotals">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetChartTotalsResult">
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>