//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass.TOne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ToneGeneratedCall> GeneratedCalls { get; set; }
    
        public virtual int FillReceivedCalls()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FillReceivedCalls");
        }
    
        public virtual int LevelTwoCompare()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LevelTwoCompare");
        }
    
        public virtual int TruncateGeneratedCalls()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateGeneratedCalls");
        }
    }
}
