//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOne.WhS.Invoice.Web.WhS_Invoice.Reports {
    
    
    public partial class Reporting {
    }
}
