CREATE TABLE [dbo].[Ol_NumberProfile] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [SubscriberNumber]   VARCHAR (30)    NULL,
    [Date_Day]           DATETIME        NULL,
    [Day_Hour]           INT             NULL,
    [Count_Out_Calls]    INT             NULL,
    [Count_In_Calls]     INT             NOT NULL,
    [Count_Out_Fail]     INT             NULL,
    [Count_In_Fail]      INT             NOT NULL,
    [Call_Out_Dur_Avg]   NUMERIC (38, 2) NULL,
    [Call_In_Dur_Avg]    NUMERIC (38, 2) NOT NULL,
    [Total_Out_Volume]   NUMERIC (38, 2) NULL,
    [Total_In_Volume]    NUMERIC (38, 2) NOT NULL,
    [Diff_Output_Numb]   INT             NULL,
    [Diff_Input_Numbers] INT             NOT NULL,
    [Diff_Dest_net]      INT             NULL,
    [Diff_Sources_net]   INT             NULL,
    [Total_BTS_In]       INT             NULL,
    [Total_BTS_Out]      INT             NULL,
    [Count_Out_SMS]      INT             NULL,
    [Count_In_SMS]       INT             NULL,
    [Total_IMEI]         INT             NULL,
    [Count_Out_OnNet]    INT             NULL,
    [Count_In_OnNet]     INT             NULL,
    [Count_Out_OffNet]   INT             NULL,
    [Count_In_OffNet]    INT             NULL,
    [Total_BTS]          INT             NULL,
    [Count_Out_Inter]    INT             NULL,
    [Count_In_Inter]     INT             NULL,
    [IsOnNet]            INT             NULL,
    [Total_Data_Volume]  DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_MobileProfilexNew] PRIMARY KEY CLUSTERED ([Id] ASC)
);

