

CREATE PROCEDURE [dbo].[bp_RT_Full_CreateRoutesIndexes]

WITH RECOMPILE
AS
BEGIN
DECLARE @Message varchar(500) 

      	SET @Message = CONVERT(varchar, getdate(), 121)
		EXEC bp_RT_Full_SetSystemMessages 'BuildRoutes: Start building INDEX for Routes', @Message   
      
			CREATE CLUSTERED INDEX [PK_TempRouteID] ON [dbo].[TempRoutes] 
			(
				[RouteID] ASC
			)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

			CREATE NONCLUSTERED INDEX [IX_TempRoutes_Zone] ON [dbo].[TempRoutes] 
			(
				[OurZoneID] ASC
			)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

			CREATE NONCLUSTERED INDEX [IX_TempRoutes_Updated] ON [dbo].[TempRoutes] 
			(
				[Updated] DESC
			)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

			CREATE NONCLUSTERED INDEX [IX_TempRoutes_Customer] ON [dbo].[TempRoutes] 
			(
				[CustomerID] ASC
			)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

			CREATE NONCLUSTERED INDEX [IX_TempRoutes_Code] ON [dbo].[TempRoutes] 
			(
				[Code] ASC
			)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

		SET @Message = CONVERT(varchar, getdate(), 121)
		EXEC bp_RT_Full_SetSystemMessages 'BuildRoutes: INDEX Built for Routes', @Message

END