//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CellProfile> CellProfiles { get; set; }
        public DbSet<Criteria_Profile> Criteria_Profile { get; set; }
        public DbSet<EmailReceiver> EmailReceivers { get; set; }
        public DbSet<EmailReceiverType> EmailReceiverTypes { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<EmailToken> EmailTokens { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<ReportDetail> ReportDetails { get; set; }
        public DbSet<ReportingStatu> ReportingStatus { get; set; }
        public DbSet<Set_CallClass> Set_CallClass { get; set; }
        public DbSet<Set_CallType> Set_CallType { get; set; }
        public DbSet<Set_SubType> Set_SubType { get; set; }
        public DbSet<Strategy> Strategies { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<NumberProfile> NumberProfiles { get; set; }
        public DbSet<Period> Periods { get; set; }
        public DbSet<Strategy1> Strategy1 { get; set; }
        public DbSet<SubscriberThreshold> SubscriberThresholds { get; set; }
        public DbSet<Suspicion_Level> Suspicion_Level { get; set; }
        public DbSet<NormalCDR> NormalCDRs { get; set; }
        public DbSet<vwReportedNumber> vwReportedNumbers { get; set; }
        public DbSet<vwReportedNumberNormalCDR> vwReportedNumberNormalCDRs { get; set; }
        public DbSet<vwReportVariable> vwReportVariables { get; set; }
        public DbSet<vwSuspectionAnalysi> vwSuspectionAnalysis { get; set; }
    
        public virtual int prCollectNormalizedCDR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCollectNormalizedCDR");
        }
    
        public virtual int prDashboard(string database)
        {
            var databaseParameter = database != null ?
                new ObjectParameter("Database", database) :
                new ObjectParameter("Database", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDashboard", databaseParameter);
        }
    
        public virtual int prDeleteEmail(string ids)
        {
            var idsParameter = ids != null ?
                new ObjectParameter("Ids", ids) :
                new ObjectParameter("Ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteEmail", idsParameter);
        }
    
        public virtual int prFillDailyCellProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillDailyCellProfile");
        }
    
        public virtual int prFillDailyProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillDailyProfile");
        }
    
        public virtual int prFillDailySubscriberThresholds(Nullable<int> strategyId)
        {
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillDailySubscriberThresholds", strategyIdParameter);
        }
    
        public virtual int prFillDailySubscriberValues()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillDailySubscriberValues");
        }
    
        public virtual int prFillHourlyCellProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillHourlyCellProfile");
        }
    
        public virtual int prFillHourlyProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillHourlyProfile");
        }
    
        public virtual int prFillHourlySubscriberThresholds(Nullable<int> strategyId)
        {
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillHourlySubscriberThresholds", strategyIdParameter);
        }
    
        public virtual int prFillHourlySubscriberValues()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillHourlySubscriberValues");
        }
    
        public virtual int prFillSubscriberThresholds(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> strategyId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillSubscriberThresholds", fromDateParameter, toDateParameter, strategyIdParameter);
        }
    
        public virtual int prFillSubscriberValues(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> strategyId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillSubscriberValues", fromDateParameter, toDateParameter, strategyIdParameter);
        }
    
        public virtual int prfindSuspicionOccurrence(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> strategyId, string suspectionList, Nullable<int> minimumOccurance)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("strategyId", strategyId) :
                new ObjectParameter("strategyId", typeof(int));
    
            var suspectionListParameter = suspectionList != null ?
                new ObjectParameter("SuspectionList", suspectionList) :
                new ObjectParameter("SuspectionList", typeof(string));
    
            var minimumOccuranceParameter = minimumOccurance.HasValue ?
                new ObjectParameter("MinimumOccurance", minimumOccurance) :
                new ObjectParameter("MinimumOccurance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prfindSuspicionOccurrence", fromDateParameter, toDateParameter, strategyIdParameter, suspectionListParameter, minimumOccuranceParameter);
        }
    
        public virtual int prGetEmails(string destinationEmail, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var destinationEmailParameter = destinationEmail != null ?
                new ObjectParameter("DestinationEmail", destinationEmail) :
                new ObjectParameter("DestinationEmail", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetEmails", destinationEmailParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual int prGetReportedNumberNormalCDR(Nullable<int> reportID)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetReportedNumberNormalCDR", reportIDParameter);
        }
    
        public virtual ObjectResult<prGetReportVariables_Result> prGetReportVariables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetReportVariables_Result>("prGetReportVariables");
        }
    
        public virtual int prGetUnNormalizedCDPN(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> switchID)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var switchIDParameter = switchID.HasValue ?
                new ObjectParameter("SwitchID", switchID) :
                new ObjectParameter("SwitchID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetUnNormalizedCDPN", fromDateParameter, toDateParameter, switchIDParameter);
        }
    
        public virtual int prGetUnNormalizedCGPN(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> switchID)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var switchIDParameter = switchID.HasValue ?
                new ObjectParameter("SwitchID", switchID) :
                new ObjectParameter("SwitchID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetUnNormalizedCGPN", fromDateParameter, toDateParameter, switchIDParameter);
        }
    
        public virtual int prImportfromSwitch(Nullable<int> switchID, string dBName, Nullable<int> reference)
        {
            var switchIDParameter = switchID.HasValue ?
                new ObjectParameter("SwitchID", switchID) :
                new ObjectParameter("SwitchID", typeof(int));
    
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            var referenceParameter = reference.HasValue ?
                new ObjectParameter("Reference", reference) :
                new ObjectParameter("Reference", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prImportfromSwitch", switchIDParameter, dBNameParameter, referenceParameter);
        }
    
        public virtual int prImportfromSwitches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prImportfromSwitches");
        }
    
        public virtual int prNormalization()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prNormalization");
        }
    
        public virtual int prNumberProfiling()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prNumberProfiling");
        }
    
        public virtual int prSendMail(string profile_name, string recipients, string subject, string copy_recipients, string body, string blind_copy_recipients)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var blind_copy_recipientsParameter = blind_copy_recipients != null ?
                new ObjectParameter("blind_copy_recipients", blind_copy_recipients) :
                new ObjectParameter("blind_copy_recipients", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prSendMail", profile_nameParameter, recipientsParameter, subjectParameter, copy_recipientsParameter, bodyParameter, blind_copy_recipientsParameter);
        }
    
        public virtual int prSendMailWithAttachment(string profile_name, string recipients, string subject, string copy_recipients, string body, string file_attachments, string blind_copy_recipients)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var file_attachmentsParameter = file_attachments != null ?
                new ObjectParameter("file_attachments", file_attachments) :
                new ObjectParameter("file_attachments", typeof(string));
    
            var blind_copy_recipientsParameter = blind_copy_recipients != null ?
                new ObjectParameter("blind_copy_recipients", blind_copy_recipients) :
                new ObjectParameter("blind_copy_recipients", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prSendMailWithAttachment", profile_nameParameter, recipientsParameter, subjectParameter, copy_recipientsParameter, bodyParameter, file_attachmentsParameter, blind_copy_recipientsParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Ol_prFillDailyProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ol_prFillDailyProfile");
        }
    
        public virtual int Ol_prFillDailySubscriberThresholds(Nullable<int> strategyId)
        {
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ol_prFillDailySubscriberThresholds", strategyIdParameter);
        }
    
        public virtual int Ol_prFillHourlyProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ol_prFillHourlyProfile");
        }
    
        public virtual int Ol_prFillHourlySubscriberThresholds(Nullable<int> strategyId)
        {
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ol_prFillHourlySubscriberThresholds", strategyIdParameter);
        }
    
        public virtual int prCollectNormalizedCDR1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prCollectNormalizedCDR1");
        }
    
        public virtual int prFillDailySubscriberValues1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillDailySubscriberValues1");
        }
    
        public virtual int prFillHourlySubscriberValues1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillHourlySubscriberValues1");
        }
    
        public virtual int prFillSubscriberThresholds1(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> strategyId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillSubscriberThresholds1", fromDateParameter, toDateParameter, strategyIdParameter);
        }
    
        public virtual int prFillSubscriberValues1(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> strategyId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var strategyIdParameter = strategyId.HasValue ?
                new ObjectParameter("StrategyId", strategyId) :
                new ObjectParameter("StrategyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFillSubscriberValues1", fromDateParameter, toDateParameter, strategyIdParameter);
        }
    
        public virtual int prNumberProfiling1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prNumberProfiling1");
        }
    
        public virtual int Ranking(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ranking", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<sp_Strategy_GetAll_Result> sp_Strategy_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Strategy_GetAll_Result>("sp_Strategy_GetAll");
        }
    
        public virtual ObjectResult<sp_Strategy_GetFilteredStrategies_Result> sp_Strategy_GetFilteredStrategies(Nullable<int> fromRow, Nullable<int> toRow, string name, string description)
        {
            var fromRowParameter = fromRow.HasValue ?
                new ObjectParameter("FromRow", fromRow) :
                new ObjectParameter("FromRow", typeof(int));
    
            var toRowParameter = toRow.HasValue ?
                new ObjectParameter("ToRow", toRow) :
                new ObjectParameter("ToRow", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Strategy_GetFilteredStrategies_Result>("sp_Strategy_GetFilteredStrategies", fromRowParameter, toRowParameter, nameParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<sp_Strategy_GetStrategy_Result> sp_Strategy_GetStrategy(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Strategy_GetStrategy_Result>("sp_Strategy_GetStrategy", idParameter);
        }
    
        public virtual int sp_Strategy_Insert(Nullable<int> userId, string name, string description, Nullable<System.DateTime> creationDate, Nullable<bool> isDefault, string strategyContent, ObjectParameter id)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var creationDateParameter = creationDate.HasValue ?
                new ObjectParameter("CreationDate", creationDate) :
                new ObjectParameter("CreationDate", typeof(System.DateTime));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("IsDefault", isDefault) :
                new ObjectParameter("IsDefault", typeof(bool));
    
            var strategyContentParameter = strategyContent != null ?
                new ObjectParameter("StrategyContent", strategyContent) :
                new ObjectParameter("StrategyContent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Strategy_Insert", userIdParameter, nameParameter, descriptionParameter, creationDateParameter, isDefaultParameter, strategyContentParameter, id);
        }
    
        public virtual int sp_Strategy_Update(Nullable<int> id, Nullable<int> userId, string name, string description, Nullable<System.DateTime> creationDate, Nullable<bool> isDefault, string strategyContent)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var creationDateParameter = creationDate.HasValue ?
                new ObjectParameter("CreationDate", creationDate) :
                new ObjectParameter("CreationDate", typeof(System.DateTime));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("IsDefault", isDefault) :
                new ObjectParameter("IsDefault", typeof(bool));
    
            var strategyContentParameter = strategyContent != null ?
                new ObjectParameter("StrategyContent", strategyContent) :
                new ObjectParameter("StrategyContent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Strategy_Update", idParameter, userIdParameter, nameParameter, descriptionParameter, creationDateParameter, isDefaultParameter, strategyContentParameter);
        }
    
        public virtual ObjectResult<sp_CallClass_GetAll_Result> sp_CallClass_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CallClass_GetAll_Result>("sp_CallClass_GetAll");
        }
    
        public virtual ObjectResult<sp_NormalCDR_Load_Result> sp_NormalCDR_Load(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NormalCDR_Load_Result>("sp_NormalCDR_Load", fromParameter, toParameter);
        }
    }
}
