//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public Period()
        {
            this.ControlTables = new HashSet<ControlTable>();
            this.delete_StrategyPeriods = new HashSet<delete_StrategyPeriods>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ControlTable> ControlTables { get; set; }
        public virtual ICollection<delete_StrategyPeriods> delete_StrategyPeriods { get; set; }
    }
}
