//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedColumn
    {
        public PredefinedColumn()
        {
            this.delete_SourceMappings = new HashSet<delete_SourceMappings>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<delete_SourceMappings> delete_SourceMappings { get; set; }
    }
}
