//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strategy
    {
        public Strategy()
        {
            this.Related_Criteria = new HashSet<Related_Criteria>();
            this.ReportDetails = new HashSet<ReportDetail>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string StrategyContent { get; set; }
    
        public virtual ICollection<Related_Criteria> Related_Criteria { get; set; }
        public virtual ICollection<ReportDetail> ReportDetails { get; set; }
        public virtual User User { get; set; }
    }
}
