//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.EmailTemplates1 = new HashSet<EmailTemplate>();
            this.Imports = new HashSet<Import>();
            this.Imports1 = new HashSet<Import>();
            this.Reports = new HashSet<Report>();
            this.Reports1 = new HashSet<Report>();
            this.Strategies = new HashSet<Strategy>();
            this.Strategies1 = new HashSet<Strategy>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserPermissions1 = new HashSet<UserPermission>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsSuperUser { get; set; }
        public string VerificationCode { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplates1 { get; set; }
        public virtual ICollection<Import> Imports { get; set; }
        public virtual ICollection<Import> Imports1 { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Report> Reports1 { get; set; }
        public virtual ICollection<Strategy> Strategies { get; set; }
        public virtual ICollection<Strategy> Strategies1 { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<UserPermission> UserPermissions1 { get; set; }
    }
}
