CREATE TABLE [dbo].[Strategy_Suspicion_Level] (
    [Id]           INT             IDENTITY (1, 1) NOT NULL,
    [StrategyId]   INT             NULL,
    [LevelId]      INT             NULL,
    [CriteriaId1]  INT             NULL,
    [Cr1Per]       DECIMAL (18, 2) NULL,
    [CriteriaId2]  INT             NULL,
    [Cr2Per]       DECIMAL (18, 2) NULL,
    [CriteriaId3]  INT             NULL,
    [Cr3Per]       DECIMAL (18, 2) NULL,
    [CriteriaId4]  INT             NULL,
    [Cr4Per]       DECIMAL (18, 2) NULL,
    [CriteriaId5]  INT             NULL,
    [Cr5Per]       DECIMAL (18, 2) NULL,
    [CriteriaId6]  INT             NULL,
    [Cr6Per]       DECIMAL (18, 2) NULL,
    [CriteriaId7]  INT             NULL,
    [Cr7Per]       DECIMAL (18, 2) NULL,
    [CriteriaId8]  INT             NULL,
    [Cr8Per]       DECIMAL (18, 2) NULL,
    [CriteriaId9]  INT             NULL,
    [Cr9Per]       DECIMAL (18, 2) NULL,
    [CriteriaId10] INT             NULL,
    [Cr10Per]      DECIMAL (18, 2) NULL,
    [CriteriaId11] INT             NULL,
    [Cr11Per]      DECIMAL (18, 2) NULL,
    [CriteriaId12] INT             NULL,
    [Cr12Per]      DECIMAL (18, 2) NULL,
    [CriteriaId13] INT             NULL,
    [Cr13Per]      DECIMAL (18, 2) NULL,
    [CriteriaId14] INT             NULL,
    [Cr14Per]      DECIMAL (18, 2) NULL,
    [CriteriaId15] INT             NULL,
    [Cr15Per]      DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_Strategy_suspection_level] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Strategy_suspection_level_Strategy] FOREIGN KEY ([StrategyId]) REFERENCES [dbo].[Strategy] ([Id]),
    CONSTRAINT [FK_Strategy_suspection_level_suspection_level] FOREIGN KEY ([LevelId]) REFERENCES [dbo].[Suspicion_Level] ([Id])
);

