CREATE TABLE [dbo].[Temp_Billing_CDR_Invalid] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [Attempt]           DATETIME        NULL,
    [Alert]             DATETIME        NULL,
    [Connect]           DATETIME        NULL,
    [Disconnect]        DATETIME        NULL,
    [DurationInSeconds] NUMERIC (13, 4) NULL,
    [CustomerID]        VARCHAR (5)     NULL,
    [OurZoneID]         INT             NULL,
    [SupplierID]        VARCHAR (5)     NULL,
    [SupplierZoneID]    INT             NULL,
    [CDPN]              VARCHAR (50)    NULL,
    [CGPN]              VARCHAR (50)    NULL,
    [ReleaseCode]       VARCHAR (50)    NULL,
    [ReleaseSource]     VARCHAR (10)    NULL,
    [SwitchID]          TINYINT         NULL,
    [SwitchCdrID]       BIGINT          NULL,
    [Tag]               VARCHAR (50)    NULL,
    [OriginatingZoneID] INT             NULL,
    [Extra_Fields]      VARCHAR (255)   NULL,
    [IsRerouted]        CHAR (1)        NULL,
    [Port_IN]           VARCHAR (42)    NULL,
    [Port_OUT]          VARCHAR (42)    NULL,
    [OurCode]           VARCHAR (20)    NULL,
    [SupplierCode]      VARCHAR (20)    NULL,
    [CDPNOut]           VARCHAR (50)    NULL,
    [SubscriberID]      BIGINT          NULL,
    [SIP]               VARCHAR (100)   NULL
);

