CREATE TYPE [TOneWhS_Analytics].[BillingWIthTrafficStatsDailyType] AS TABLE (
    [ID]                     BIGINT          NULL,
    [BatchStart]             DATETIME        NULL,
    [CustomerID]             INT             NULL,
    [OurZoneID]              BIGINT          NULL,
    [SupplierID]             INT             NULL,
    [SupplierZoneID]         BIGINT          NULL,
    [CustomerProfileID]      INT             NULL,
    [SupplierProfileID]      INT             NULL,
    [SaleCurrencyID]         INT             NULL,
    [CostCurrencyID]         INT             NULL,
    [LastCDRAttempt]         DATETIME        NULL,
    [Attempts]               INT             NULL,
    [DeliveredAttempts]      INT             NULL,
    [SuccessfulAttempts]     INT             NULL,
    [NumberOfCalls]          INT             NULL,
    [DeliveredNumberOfCalls] INT             NULL,
    [DurationInSeconds]      DECIMAL (20, 4) NULL,
    [SumOfPDDInSeconds]      DECIMAL (20)    NULL,
    [PricedCalls]            INT             NULL,
    [SaleNet]                DECIMAL (20, 5) NULL,
    [SaleDurationInSeconds]  DECIMAL (20, 4) NULL,
    [CostNet]                DECIMAL (20, 5) NULL,
    [CostDurationInSeconds]  DECIMAL (20, 4) NULL);

