//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDR
    {
        public int Id { get; set; }
        public string MSISDN { get; set; }
        public string IMSI { get; set; }
        public Nullable<System.DateTime> ConnectDateTime { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> DurationInSeconds { get; set; }
        public Nullable<System.DateTime> DisconnectDateTime { get; set; }
        public string Call_Class { get; set; }
        public Nullable<int> Call_Type { get; set; }
        public string Sub_Type { get; set; }
        public string IMEI { get; set; }
        public Nullable<int> BTS_Id { get; set; }
        public string LAC { get; set; }
        public string Cell_Id { get; set; }
        public string Origin_Zone_Code { get; set; }
        public string Termin_Zone_Code { get; set; }
        public Nullable<System.DateTime> Account_Age { get; set; }
        public string Reference { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ImportID { get; set; }
        public string Switch { get; set; }
        public Nullable<int> Ignore { get; set; }
        public Nullable<bool> IsNormalized { get; set; }
    }
}
