//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailReceiver
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<int> EmailTemplateID { get; set; }
        public Nullable<int> EmailReceiverTypeID { get; set; }
    
        public virtual EmailReceiverType EmailReceiverType { get; set; }
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}
