//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.MobileCDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberThreshold
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateDay { get; set; }
        public string SubscriberNumber { get; set; }
        public Nullable<int> Criteria1 { get; set; }
        public Nullable<int> Criteria2 { get; set; }
        public Nullable<int> Criteria3 { get; set; }
        public Nullable<int> Criteria4 { get; set; }
        public Nullable<int> Criteria5 { get; set; }
        public Nullable<int> Criteria6 { get; set; }
        public Nullable<int> SuspectionLevelId { get; set; }
        public Nullable<int> StrategyId { get; set; }
    
        public virtual Suspicion_Level Suspicion_Level { get; set; }
    }
}
