<?xml version="1.0" encoding="utf-8"?><Database Name="CLITester" Class="CallGeneratorModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CLITester;User ID=sa" SettingsObjectName="CallGeneratorLibrary.Properties.Settings" SettingsPropertyName="FraudTest2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Exceptions" Member="Exceptions">
    <Type Name="Exception">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ExceptionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="DataCalls">
    <Type Name="DataCalls">
      <Column Name="Id" Type="System.Int32" CanBeNull="true" />
      <Column Name="OperatorId" Type="System.Int32" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" CanBeNull="true" />
      <Column Name="MSISDN" Type="System.String" CanBeNull="true" />
      <Column Name="AndroidDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="EndCall" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" CanBeNull="true" />
      <Column Name="Name" Type="System.String" CanBeNull="true" />
      <Column Name="Country" Type="System.String" CanBeNull="true" />
      <Column Name="mcc" Type="System.String" CanBeNull="true" />
      <Column Name="mnc" Type="System.String" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="ChartCalls">
    <Type Name="ChartCalls">
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="TotalCalls" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="TestOperatorHistories">
    <Type Name="TestOperatorHistory" Id="ID1">
      <Column Name="Name" Type="System.String" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" CanBeNull="true" />
      <Column Name="RowCount" Type="System.Int32" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" CanBeNull="true" />
      <Column Name="Route" Type="System.String" CanBeNull="false" />
      <Column Name="ErrorMessage" Type="System.String" CanBeNull="false" />
      <Column Name="PDD" Type="System.String" CanBeNull="false" />
      <Column Name="Duration" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Operators" Member="Operators">
    <Type Name="Operator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mcc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mnc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryPicture" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ServiceAndroid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ServiceMonty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Operator_ScheduleOperator" Member="ScheduleOperators" ThisKey="Id" OtherKey="OperatorId" Type="ScheduleOperator" />
      <Association Name="Operator_TestOperator" Member="TestOperators" ThisKey="Id" OtherKey="OperatorId" Type="TestOperator" />
    </Type>
  </Table>
  <Table Name="dbo.ActionLog" Member="ActionLogs">
    <Type Name="ActionLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RemoteAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComputerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_ActionLog" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleOperators" Member="ScheduleOperators">
    <Type Name="ScheduleOperator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarrierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Operator_ScheduleOperator" Member="Operator" ThisKey="OperatorId" OtherKey="Id" Type="Operator" IsForeignKey="true" />
      <Association Name="Schedule_ScheduleOperator" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="Carrier_ScheduleOperator" Member="Carrier" ThisKey="CarrierId" OtherKey="Id" Type="Carrier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OperatorLogs" Member="OperatorLogs">
    <Type Name="OperatorLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MCC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MNC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IsOnline" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeFrequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MonthDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OccursEvery" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecificTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TotalNumbers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatioOfCalls" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecificTime1" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="Schedule_ScheduleOperator" Member="ScheduleOperators" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleOperator" />
      <Association Name="Schedule_TestOperator" Member="TestOperators" ThisKey="Id" OtherKey="ScheduleId" Type="TestOperator" />
      <Association Name="Schedule_ScheduleLog" Member="ScheduleLogs" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleLog" />
      <Association Name="SipAccount_Schedule" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_Schedule" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserBalances" Member="UserBalances">
    <Type Name="UserBalance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldBalance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneratedCalls" Member="GeneratedCalls">
    <Type Name="GeneratedCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartCall" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AlertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConnectDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DisconnectDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SipAccount_GeneratedCall" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestOperators" Member="TestOperators">
    <Type Name="TestOperator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarrierPrefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CallerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Requested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhonePrefix" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PDD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Duration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TestOperator_MontyCall" Member="MontyCalls" ThisKey="Id" OtherKey="TestOperatorId" Type="MontyCall" />
      <Association Name="Operator_TestOperator" Member="Operator" ThisKey="OperatorId" OtherKey="Id" Type="Operator" IsForeignKey="true" />
      <Association Name="Schedule_TestOperator" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="User_TestOperator" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ActionLogFeeds">
    <Type Name="ActionLogFeed">
      <Column Name="Id" Type="System.Int32" CanBeNull="true" />
      <Column Name="ActionType" Type="System.Int32" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" CanBeNull="true" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MontyCalls" Member="MontyCalls">
    <Type Name="MontyCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestOperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSISDN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GeneratedCallId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestOperator_MontyCall" Member="TestOperator" ThisKey="TestOperatorId" OtherKey="Id" Type="TestOperator" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleLogs" Member="ScheduleLogs">
    <Type Name="ScheduleLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_ScheduleLog" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Carriers" Member="Carriers">
    <Type Name="Carrier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Carrier_ScheduleOperator" Member="ScheduleOperators" ThisKey="Id" OtherKey="CarrierId" Type="ScheduleOperator" />
    </Type>
  </Table>
  <Table Name="dbo.SipAccounts" Member="SipAccounts">
    <Type Name="SipAccount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Server" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UseProxy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProxyServer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ProxyUser" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ProxyPass" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TotalLines" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseAudio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultAudioFileName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DefaultAudioFile" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PlaybackDevice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NetworkInterface" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Codecs" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsChangedCallerId" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BeginRechargeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberOfMonths" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BalanceValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SipAccount_Schedule" Member="Schedules" ThisKey="Id" OtherKey="SipAccountId" Type="Schedule" />
      <Association Name="SipAccount_GeneratedCall" Member="GeneratedCalls" ThisKey="Id" OtherKey="SipAccountId" Type="GeneratedCall" />
    </Type>
  </Table>
  <Table Name="dbo.BalanceDetails" Member="BalanceDetails">
    <Type Name="BalanceDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remaining" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeginEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContractId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contract_BalanceDetail" Member="Contract" ThisKey="ContractId" OtherKey="Id" Type="Contract" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ContractDetails">
    <Type Name="ContractDetails">
      <Column Name="NumberOfCalls" Type="System.Int32" CanBeNull="true" />
      <Column Name="NumberOfPeriod" Type="System.Int32" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contract" Member="Contracts">
    <Type Name="Contract">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChargeType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsDone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Contract_BalanceDetail" Member="BalanceDetails" ThisKey="Id" OtherKey="ContractId" Type="BalanceDetail" />
    </Type>
  </Table>
  <Table Name="" Member="ContractFields">
    <Type Name="ContractFields">
      <Column Name="Id" Type="System.Int32" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ChargeType" Type="System.String" CanBeNull="true" />
      <Column Name="NumberOfCalls" Type="System.Int32" CanBeNull="true" />
      <Column Name="NumberOfPeriod" Type="System.Int32" CanBeNull="true" />
      <Column Name="Period" Type="System.String" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Guid" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WebsiteURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RemainingBalance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastSetBalance" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_ActionLog" Member="ActionLogs" ThisKey="Id" OtherKey="UserId" Type="ActionLog" />
      <Association Name="User_Schedule" Member="Schedules" ThisKey="Id" OtherKey="UserId" Type="Schedule" />
      <Association Name="User_TestOperator" Member="TestOperators" ThisKey="Id" OtherKey="UserId" Type="TestOperator" />
    </Type>
  </Table>
  <Function Name="dbo.GetData" Method="GetData">
    <ElementType Name="GetDataResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSISDN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AndroidDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndCall" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mcc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mnc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetChartTotals" Method="GetChartTotals">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetChartTotalsResult">
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTestOperators" Method="GetTestOperators">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="OperatorId" Parameter="operatorId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayStart" Parameter="displayStart" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayLength" Parameter="displayLength" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetActionLogs" Method="GetActionLogs">
    <Parameter Name="ObjectType" Parameter="objectType" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetActionLogsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>