<?xml version="1.0" encoding="utf-8"?><Database Name="FraudTest" Class="CallGeneratorModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LENOVO\SQL2008R2;Initial Catalog=FraudTest;Persist Security Info=True;User ID=sa" SettingsObjectName="CallGeneratorLibrary.Properties.Settings" SettingsPropertyName="FraudTest2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SipStatus" Member="SipStatus">
    <Type Name="SipStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="SipStatus_CallEntryDetail" Member="CallEntryDetails" ThisKey="Id" OtherKey="StatusId" Type="CallEntryDetail" />
    </Type>
  </Table>
  <Table Name="dbo.CallEntryStatus" Member="CallEntryStatus">
    <Type Name="CallEntryStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="CallEntryStatus_CallEntry" Member="CallEntries" ThisKey="Id" OtherKey="StatusId" Type="CallEntry" />
    </Type>
  </Table>
  <Table Name="dbo.CallSessions" Member="CallSessions">
    <Type Name="CallSession">
      <Column Name="SessionId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CheckAfter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CallerId" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CallSession_CallEntry" Member="CallEntries" ThisKey="SessionId" OtherKey="SessionId" Type="CallEntry" />
      <Association Name="Schedule_CallSession" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="SipAccount_CallSession" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Exceptions" Member="Exceptions">
    <Type Name="Exception">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ExceptionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CallEntryDetails" Member="CallEntryDetails">
    <Type Name="CallEntryDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CallEntriesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SipStatus_CallEntryDetail" Member="SipStatus" ThisKey="StatusId" OtherKey="Id" Type="SipStatus" IsForeignKey="true" />
      <Association Name="CallEntry_CallEntryDetail" Member="CallEntry" ThisKey="CallEntriesId" OtherKey="Id" Type="CallEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleWeekDays" Member="ScheduleWeekDays">
    <Type Name="ScheduleWeekDay">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_ScheduleWeekDay" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.CallGeneratorLogEntries" Member="CallGeneratorLogEntries">
    <Type Name="CallGeneratorLogEntry">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleLogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Number" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ConnectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LineId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SessionId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ScheduleLog_CallGeneratorLogEntry" Member="ScheduleLog" ThisKey="ScheduleLogId" OtherKey="Id" Type="ScheduleLog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleNumbers" Member="ScheduleNumbers">
    <Type Name="ScheduleNumber">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Schedule_ScheduleNumber" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lookups" Member="Lookups">
    <Type Name="Lookup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Lookup_LookupValue" Member="LookupValues" ThisKey="Id" OtherKey="LookupId" Type="LookupValue" />
    </Type>
  </Table>
  <Table Name="dbo.LookupValues" Member="LookupValues">
    <Type Name="LookupValue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameAr" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameEn" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NameFr" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LookupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LookValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lookup_LookupValue" Member="Lookup" ThisKey="LookupId" OtherKey="Id" Type="Lookup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page" Id="ID1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Page_PagesPermission" Member="PagesPermissions" ThisKey="Id" OtherKey="PageId" Type="PagesPermission" />
    </Type>
  </Table>
  <Table Name="dbo.PagesPermissions" Member="PagesPermissions">
    <Type Name="PagesPermission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Page_PagesPermission" Member="Page" ThisKey="PageId" OtherKey="Id" Type="Page" IsForeignKey="true" />
      <Association Name="Permission_PagesPermission" Member="Permission" ThisKey="PermissionId" OtherKey="Id" Type="Permission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permissions" Member="Permissions">
    <Type Name="Permission" Id="ID3">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Permission_PagesPermission" Member="PagesPermissions" ThisKey="Id" OtherKey="PermissionId" Type="PagesPermission" />
      <Association Name="Permission_RolePermission" Member="RolePermissions" ThisKey="Id" OtherKey="PermissionId" Type="RolePermission" />
    </Type>
  </Table>
  <Table Name="dbo.RolePermissions" Member="RolePermissions">
    <Type Name="RolePermission" Id="ID2">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CanAdd" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Permission_RolePermission" Member="Permission" ThisKey="PermissionId" OtherKey="Id" Type="Permission" IsForeignKey="true" />
      <Association Name="Role_RolePermission" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role" Id="ID5">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Role_RolePermission" Member="RolePermissions" ThisKey="Id" OtherKey="RoleId" Type="RolePermission" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Carriers" Member="Carriers">
    <Type Name="Carrier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Prefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Carrier_ScheduleOperator" Member="ScheduleOperators" ThisKey="Id" OtherKey="CarrierId" Type="ScheduleOperator" />
      <Association Name="User_Carrier" Member="User" ThisKey="CustomerId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeFrequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MonthDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OccursEvery" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecificTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="TotalNumbers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RatioOfCalls" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_CallSession" Member="CallSessions" ThisKey="Id" OtherKey="ScheduleId" Type="CallSession" />
      <Association Name="Schedule_ScheduleWeekDay" Member="ScheduleWeekDays" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleWeekDay" />
      <Association Name="Schedule_ScheduleNumber" Member="ScheduleNumbers" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleNumber" />
      <Association Name="Schedule_ScheduleOperator" Member="ScheduleOperators" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleOperator" />
      <Association Name="Schedule_ScheduleGroup" Member="ScheduleGroups" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleGroup" />
      <Association Name="Schedule_ScheduleLog" Member="ScheduleLogs" ThisKey="Id" OtherKey="ScheduleId" Type="ScheduleLog" />
      <Association Name="Schedule_TestOperator" Member="TestOperators" ThisKey="Id" OtherKey="ScheduleId" Type="TestOperator" />
      <Association Name="SipAccount_Schedule" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_Schedule" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleOperators" Member="ScheduleOperators">
    <Type Name="ScheduleOperator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarrierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Carrier_ScheduleOperator" Member="Carrier" ThisKey="CarrierId" OtherKey="Id" Type="Carrier" IsForeignKey="true" />
      <Association Name="Schedule_ScheduleOperator" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="Operator_ScheduleOperator" Member="Operator" ThisKey="OperatorId" OtherKey="Id" Type="Operator" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestNumbers" Member="TestNumbers">
    <Type Name="TestNumber">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeletionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PrefixId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CounterUsage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SuccessfulAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestNumberGroup_TestNumber" Member="TestNumberGroup" ThisKey="GroupId" OtherKey="Id" Type="TestNumberGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleGroups" Member="ScheduleGroups">
    <Type Name="ScheduleGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schedule_ScheduleGroup" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="TestNumberGroup_ScheduleGroup" Member="TestNumberGroup" ThisKey="GroupId" OtherKey="Id" Type="TestNumberGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Thread" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Logger" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Exception" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TestNumberGroups" Member="TestNumberGroups">
    <Type Name="TestNumberGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TestNumberGroup_TestNumber" Member="TestNumbers" ThisKey="Id" OtherKey="GroupId" Type="TestNumber" />
      <Association Name="TestNumberGroup_ScheduleGroup" Member="ScheduleGroups" ThisKey="Id" OtherKey="GroupId" Type="ScheduleGroup" />
      <Association Name="TestNumberGroup_TestNumber1" Member="TestNumber1s" ThisKey="Id" OtherKey="GroupId" Type="TestNumber1" />
    </Type>
  </Table>
  <Table Name="dbo.TestNumbers" Member="TestNumber1s">
    <Type Name="TestNumber1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DeletionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PrefixId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CounterUsage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SuccessfulAttempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestNumberGroup_TestNumber1" Member="TestNumberGroup" ThisKey="GroupId" OtherKey="Id" Type="TestNumberGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CallEntries" Member="CallEntries">
    <Type Name="CallEntry">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsProcessed" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SessionId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cgpn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CallEntry_CallEntryDetail" Member="CallEntryDetails" ThisKey="Id" OtherKey="CallEntriesId" Type="CallEntryDetail" />
      <Association Name="CallEntryStatus_CallEntry" Member="CallEntryStatus" ThisKey="StatusId" OtherKey="Id" Type="CallEntryStatus" IsForeignKey="true" />
      <Association Name="CallSession_CallEntry" Member="CallSession" ThisKey="SessionId" OtherKey="SessionId" Type="CallSession" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CDR" Member="CDRs">
    <Type Name="CDR">
      <Column Name="CDRID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDonSwitch" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AttemptDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AlertDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConnectDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DisconnectDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DurationInSeconds" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IN_TRUNK" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IN_CIRCUIT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IN_CARRIER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IN_IP" Type="System.String" DbType="VarChar(21)" CanBeNull="true" />
      <Column Name="OUT_TRUNK" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OUT_CIRCUIT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OUT_CARRIER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OUT_IP" Type="System.String" DbType="VarChar(21)" CanBeNull="true" />
      <Column Name="CGPN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CDPN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CAUSE_FROM_RELEASE_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CAUSE_FROM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CAUSE_TO_RELEASE_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CAUSE_TO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Extra_Fields" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsRerouted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CDPNOut" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SIP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TransactionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecievedCLI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GeneratedCalls" Member="GeneratedCalls">
    <Type Name="GeneratedCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartCall" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SipAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GeneratedCall_MontyCall" Member="MontyCalls" ThisKey="Id" OtherKey="CallEntryId" Type="MontyCall" />
      <Association Name="SipAccount_GeneratedCall" Member="SipAccount" ThisKey="SipAccountId" OtherKey="Id" Type="SipAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SipAccounts" Member="SipAccounts">
    <Type Name="SipAccount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Server" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UseProxy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProxyServer" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ProxyUser" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ProxyPass" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TotalLines" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseAudio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DefaultAudioFileName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DefaultAudioFile" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PlaybackDevice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NetworkInterface" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Codecs" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SipAccount_CallSession" Member="CallSessions" ThisKey="Id" OtherKey="SipAccountId" Type="CallSession" />
      <Association Name="SipAccount_Schedule" Member="Schedules" ThisKey="Id" OtherKey="SipAccountId" Type="Schedule" />
      <Association Name="SipAccount_GeneratedCall" Member="GeneratedCalls" ThisKey="Id" OtherKey="SipAccountId" Type="GeneratedCall" />
      <Association Name="User_SipAccount" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleLogs" Member="ScheduleLogs">
    <Type Name="ScheduleLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IsSuccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ScheduleLog_CallGeneratorLogEntry" Member="CallGeneratorLogEntries" ThisKey="Id" OtherKey="ScheduleLogId" Type="CallGeneratorLogEntry" />
      <Association Name="Schedule_ScheduleLog" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="" Member="DataCalls">
    <Type Name="DataCalls">
      <Column Name="Id" Type="System.Int32" CanBeNull="true" />
      <Column Name="OperatorId" Type="System.Int32" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" CanBeNull="true" />
      <Column Name="MSISDN" Type="System.String" CanBeNull="true" />
      <Column Name="AndroidDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="EndCall" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" CanBeNull="true" />
      <Column Name="Name" Type="System.String" CanBeNull="true" />
      <Column Name="Country" Type="System.String" CanBeNull="true" />
      <Column Name="mcc" Type="System.String" CanBeNull="true" />
      <Column Name="mnc" Type="System.String" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="ChartCalls">
    <Type Name="ChartCalls">
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="TotalCalls" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User" Id="ID4">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSuperAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Guid" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="IpSwitch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CallerId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WebsiteURL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsChangedCallerId" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="UserId" Type="UserRole" />
      <Association Name="User_Carrier" Member="Carriers" ThisKey="Id" OtherKey="CustomerId" Type="Carrier" />
      <Association Name="User_Schedule" Member="Schedules" ThisKey="Id" OtherKey="UserId" Type="Schedule" />
      <Association Name="User_SipAccount" Member="SipAccounts" ThisKey="Id" OtherKey="UserId" Type="SipAccount" />
      <Association Name="User_ActionLog" Member="ActionLogs" ThisKey="Id" OtherKey="UserId" Type="ActionLog" />
      <Association Name="User_TestOperator" Member="TestOperators" ThisKey="Id" OtherKey="UserId" Type="TestOperator" />
    </Type>
  </Table>
  <Table Name="" Member="TestOperatorHistories">
    <Type Name="TestOperatorHistory">
      <Column Name="Name" Type="System.String" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" CanBeNull="true" />
      <Column Name="RowCount" Type="System.Int32" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Operators" Member="Operators">
    <Type Name="Operator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mcc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mnc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CountryPicture" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ServiceAndroid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ServiceMonty" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Operator_ScheduleOperator" Member="ScheduleOperators" ThisKey="Id" OtherKey="OperatorId" Type="ScheduleOperator" />
      <Association Name="Operator_TestOperator" Member="TestOperators" ThisKey="Id" OtherKey="OperatorId" Type="TestOperator" />
    </Type>
  </Table>
  <Table Name="dbo.MontyCalls" Member="MontyCalls">
    <Type Name="MontyCall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestOperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSISDN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CallDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReturnMessage" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CallEntryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GeneratedCall_MontyCall" Member="GeneratedCall" ThisKey="CallEntryId" OtherKey="Id" Type="GeneratedCall" IsForeignKey="true" />
      <Association Name="TestOperator_MontyCall" Member="TestOperator" ThisKey="TestOperatorId" OtherKey="Id" Type="TestOperator" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActionLog" Member="ActionLogs">
    <Type Name="ActionLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RemoteAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ComputerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_ActionLog" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ActionLogFeeds">
    <Type Name="ActionLogFeed">
      <Column Name="Id" Type="System.Int32" CanBeNull="true" />
      <Column Name="ActionType" Type="System.Int32" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" CanBeNull="true" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TestOperators" Member="TestOperators">
    <Type Name="TestOperator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberOfCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CarrierPrefix" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CallerId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Requested" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TestOperator_MontyCall" Member="MontyCalls" ThisKey="Id" OtherKey="TestOperatorId" Type="MontyCall" />
      <Association Name="Operator_TestOperator" Member="Operator" ThisKey="OperatorId" OtherKey="Id" Type="Operator" IsForeignKey="true" />
      <Association Name="Schedule_TestOperator" Member="Schedule" ThisKey="ScheduleId" OtherKey="Id" Type="Schedule" IsForeignKey="true" />
      <Association Name="User_TestOperator" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetRolePages" Method="GetRolePages">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.String" DbType="NVarChar(255)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetRolePermissionActions" Method="GetRolePermissionActions">
    <Parameter Name="RoleIds" Parameter="roleIds" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PageName" Parameter="pageName" Type="System.String" DbType="NVarChar(255)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.GetRolePermissions" Method="GetRolePermissions">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.GetRoleUsers" Method="GetRoleUsers">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.GetUserRoles" Method="GetUserRoles">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.GetData" Method="GetData">
    <ElementType Name="GetDataResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TestCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReceivedCli" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSISDN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AndroidDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndCall" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResponseCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mcc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="mnc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetChartTotals" Method="GetChartTotals">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetChartTotalsResult">
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalCalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTestOperators" Method="GetTestOperators" IsComposable="true">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="OperatorId" Parameter="operatorId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayStart" Parameter="displayStart" Type="System.Int32" DbType="Int" />
    <Parameter Name="DisplayLength" Parameter="displayLength" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.GetActionLogs" Method="GetActionLogs">
    <Parameter Name="ObjectType" Parameter="objectType" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetActionLogsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>