CREATE TABLE [dbo].[Fact_Cases] (
    [FK_IMEI]               VARCHAR (20)    NULL,
    [FK_MSISDN]             VARCHAR (30)    NULL,
    [MS_CaseId]             INT             NULL,
    [MS_Duration]           DECIMAL (13, 4) NULL,
    [FK_CallClass]          INT             NULL,
    [FK_CallType]           INT             NULL,
    [FK_CaseStatus]         INT             NULL,
    [FK_NetworkType]        INT             NULL,
    [FK_Period]             INT             NULL,
    [FK_Strategy]           INT             NULL,
    [FK_StrategyKind]       INT             NULL,
    [FK_SubscriberType]     VARCHAR (20)    NULL,
    [FK_SuspicionLevel]     INT             NULL,
    [FK_CaseGenerationTime] DATETIME        NULL,
    [FK_StrategyUser]       INT             NULL,
    [FK_CaseUser]           INT             NULL,
    [FK_BTS]                INT             NULL,
    [FK_AccountStatus]      INT             NULL,
    CONSTRAINT [FK_Fact_Cases_Dim_AccountStatus] FOREIGN KEY ([FK_AccountStatus]) REFERENCES [dbo].[Dim_AccountStatus] ([Pk_AccountStatusId]),
    CONSTRAINT [FK_Fact_Cases_Dim_CallClass] FOREIGN KEY ([FK_CallClass]) REFERENCES [dbo].[Dim_CallClass] ([Pk_CallClassId]),
    CONSTRAINT [FK_Fact_Cases_Dim_CallType] FOREIGN KEY ([FK_CallType]) REFERENCES [dbo].[Dim_CallType] ([Pk_CallTypeId]),
    CONSTRAINT [FK_Fact_Cases_Dim_CaseStatus] FOREIGN KEY ([FK_CaseStatus]) REFERENCES [dbo].[Dim_CaseStatus] ([Pk_CaseStatusId]),
    CONSTRAINT [FK_Fact_Cases_Dim_IMEI] FOREIGN KEY ([FK_IMEI]) REFERENCES [dbo].[Dim_IMEI] ([IMEI]),
    CONSTRAINT [FK_Fact_Cases_Dim_MSISDN] FOREIGN KEY ([FK_MSISDN]) REFERENCES [dbo].[Dim_MSISDN] ([MSISDN]),
    CONSTRAINT [FK_Fact_Cases_Dim_NetworkType] FOREIGN KEY ([FK_NetworkType]) REFERENCES [dbo].[Dim_NetworkType] ([Pk_NetTypeId]),
    CONSTRAINT [FK_Fact_Cases_Dim_Period] FOREIGN KEY ([FK_Period]) REFERENCES [dbo].[Dim_Period] ([Pk_PeriodId]),
    CONSTRAINT [FK_Fact_Cases_Dim_Strategy] FOREIGN KEY ([FK_Strategy]) REFERENCES [dbo].[Dim_Strategy] ([Pk_StrategyId]),
    CONSTRAINT [FK_Fact_Cases_Dim_StrategyKind] FOREIGN KEY ([FK_StrategyKind]) REFERENCES [dbo].[Dim_StrategyKind] ([PK_KindId]),
    CONSTRAINT [FK_Fact_Cases_Dim_SubscriberType] FOREIGN KEY ([FK_SubscriberType]) REFERENCES [dbo].[Dim_SubscriberType] ([Name]),
    CONSTRAINT [FK_Fact_Cases_Dim_SuspicionLevel] FOREIGN KEY ([FK_SuspicionLevel]) REFERENCES [dbo].[Dim_SuspicionLevel] ([Pk_SuspicionLevelId]),
    CONSTRAINT [FK_Fact_Cases_Dim_Time] FOREIGN KEY ([FK_CaseGenerationTime]) REFERENCES [dbo].[Dim_Time] ([DateInstance]),
    CONSTRAINT [FK_Fact_Cases_Dim_Users] FOREIGN KEY ([FK_StrategyUser]) REFERENCES [dbo].[Dim_Users] ([Pk_UserId])
);

