CREATE TABLE [dbo].[Fact_Calls] (
    [MS_TotalOutCallls]             INT             NULL,
    [MS_TotalInCalls]               INT             NULL,
    [MS_TotalOutSms]                INT             NULL,
    [MS_TotalInSms]                 INT             NULL,
    [MS_TotalInVolume]              INT             NULL,
    [MS_TotalOutVolume]             INT             NULL,
    [MS_TotalOutInternational]      INT             NULL,
    [MS_TotalInInternational]       INT             NULL,
    [MS_PercOnNetOriginated]        DECIMAL (18, 2) NULL,
    [MS_PercOffNetOriginated]       DECIMAL (18, 2) NULL,
    [MS_PercOnNetTerminated]        DECIMAL (18, 2) NULL,
    [MS_PercOffNetTerminated]       DECIMAL (18, 2) NULL,
    [MS_AvgOutCalls_MSISDN]         DECIMAL (18, 2) NULL,
    [MS_AvgInCalls_MSISDN]          DECIMAL (18, 2) NULL,
    [MS_AvgOutSMS_MSISDN]           DECIMAL (18, 2) NULL,
    [MS_AvgInSMS_MSISDN]            DECIMAL (18, 2) NULL,
    [MS_AvgCalledParties_MSISDN]    DECIMAL (18, 2) NULL,
    [MS_AvgBTS_MSISDN]              DECIMAL (18, 2) NULL,
    [MS_AvgDurationIn_MSISDN]       DECIMAL (18, 2) NULL,
    [MS_AvgDurationOut_MSISDN]      DECIMAL (18, 2) NULL,
    [MS_AvgOffNetOriginated_MSISDN] DECIMAL (18, 2) NULL,
    [MS_AvgOnNetOriginated_MSISDN]  DECIMAL (18, 2) NULL,
    [FK_PeriodId]                   INT             NULL,
    [FK_ConnectTime]                DATETIME        NULL,
    CONSTRAINT [FK_Fact_Calls_Dim_Period] FOREIGN KEY ([FK_PeriodId]) REFERENCES [dbo].[Dim_Period] ([Pk_PeriodId]),
    CONSTRAINT [FK_Fact_Calls_Dim_Time] FOREIGN KEY ([FK_ConnectTime]) REFERENCES [dbo].[Dim_Time] ([DateInstance])
);

