CREATE TABLE [dbo].[NortelCDR] (
    [CDRID]                   BIGINT          IDENTITY (236035150, 1) NOT NULL,
    [SwitchID]                TINYINT         NOT NULL,
    [IDonSwitch]              BIGINT          NULL,
    [Tag]                     VARCHAR (30)    NULL,
    [AttemptDateTime]         DATETIME        NULL,
    [AlertDateTime]           DATETIME        NULL,
    [ConnectDateTime]         DATETIME        NULL,
    [DisconnectDateTime]      DATETIME        NULL,
    [DurationInSeconds]       NUMERIC (13, 4) NULL,
    [IN_TRUNK]                VARCHAR (5)     NULL,
    [IN_CIRCUIT]              SMALLINT        NULL,
    [IN_CARRIER]              VARCHAR (100)   NULL,
    [IN_IP]                   VARCHAR (21)    NULL,
    [OUT_TRUNK]               VARCHAR (5)     NULL,
    [OUT_CIRCUIT]             SMALLINT        NULL,
    [OUT_CARRIER]             VARCHAR (100)   NULL,
    [OUT_IP]                  VARCHAR (21)    NULL,
    [CGPN]                    VARCHAR (40)    NULL,
    [CDPN]                    VARCHAR (40)    NULL,
    [CAUSE_FROM_RELEASE_CODE] VARCHAR (20)    NULL,
    [CAUSE_FROM]              VARCHAR (10)    NULL,
    [CAUSE_TO_RELEASE_CODE]   VARCHAR (20)    NULL,
    [CAUSE_TO]                VARCHAR (10)    NULL,
    [Extra_Fields]            VARCHAR (255)   NULL,
    [IsRerouted]              CHAR (1)        NULL,
    [CDPNOut]                 VARCHAR (40)    NULL,
    CONSTRAINT [PK_NortelCDR] PRIMARY KEY CLUSTERED ([CDRID] ASC)
);

