CREATE TABLE [dbo].[SettlementInvoiceDetails] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [SettlementInvoiceId] INT             NULL,
    [InvoiceId]           INT             NULL,
    [BeginDate]           DATETIME        NULL,
    [EndDate]             DATETIME        NULL,
    [IssueDate]           DATETIME        NULL,
    [DueDate]             DATETIME        NULL,
    [SupplierID]          VARCHAR (10)    NULL,
    [CustomerID]          VARCHAR (10)    NULL,
    [SerialNumber]        VARCHAR (50)    NULL,
    [Duration]            NUMERIC (19, 6) NULL,
    [Amount]              DECIMAL (13, 6) NULL,
    [CurrencyID]          VARCHAR (3)     NULL,
    [IsLocked]            CHAR (1)        NULL,
    [IsPaid]              CHAR (1)        NULL,
    [PaidDate]            SMALLDATETIME   NULL,
    [UserID]              INT             NULL,
    [InvoicePrintedNote]  VARCHAR (MAX)   NULL,
    [InvoiceNotes]        VARCHAR (MAX)   NULL,
    [VatValue]            DECIMAL (13, 6) NULL,
    [IsSent]              CHAR (1)        NULL,
    [CustomerMask]        VARCHAR (10)    NULL,
    [IsAutomatic]         CHAR (1)        NULL,
    [PaidAmount]          DECIMAL (13, 6) NULL,
    [NumberOfCalls]       INT             NULL,
    CONSTRAINT [PK_Settlement_Invoice_details] PRIMARY KEY CLUSTERED ([ID] ASC)
);

