CREATE TABLE [dbo].[ZebraCustomer] (
    [CarrierAccountID]    VARCHAR (5)     NOT NULL,
    [ReqID]               INT             NOT NULL,
    [Radius_UserID]       INT             NOT NULL,
    [IsApproved]          BIT             CONSTRAINT [DF_ZCustomerAccount_IsApproved] DEFAULT ((0)) NOT NULL,
    [ActivationStatus]    TINYINT         CONSTRAINT [DF_ZCustomerAccount_IsActive] DEFAULT ((0)) NOT NULL,
    [ActivationType]      INT             NOT NULL,
    [Balance]             DECIMAL (18, 3) CONSTRAINT [DF_ZCustomerAccount_Balance] DEFAULT ((0)) NOT NULL,
    [IsNetworkConfigured] BIT             CONSTRAINT [DF_ZCustomerAccount_IsNetworkConfigured] DEFAULT ((0)) NOT NULL,
    [TimeStamp]           ROWVERSION      NOT NULL,
    [UserAppID]           INT             NULL,
    [Notes]               VARCHAR (MAX)   NULL,
    [CustomerGMTTime]     SMALLINT        NULL,
    [CustomerCreditLimit] INT             NULL,
    [CustomerMask]        VARCHAR (50)    NULL,
    [Name]                NVARCHAR (200)  NULL,
    [CompanyName]         NVARCHAR (200)  NULL,
    [CompanyLogoName]     NVARCHAR (500)  NULL,
    [Address1]            NVARCHAR (250)  NULL,
    [Address2]            NVARCHAR (100)  NULL,
    [Address3]            NVARCHAR (100)  NULL,
    [Country]             NVARCHAR (100)  NULL,
    [City]                NVARCHAR (100)  NULL,
    [Telephone]           NVARCHAR (100)  NULL,
    [Fax]                 NVARCHAR (100)  NULL,
    [BillingContact]      NVARCHAR (200)  NULL,
    [BillingEmail]        NVARCHAR (256)  NULL,
    [PricingContact]      NVARCHAR (200)  NULL,
    [PricingEmail]        NVARCHAR (256)  NULL,
    [SupportContact]      NVARCHAR (200)  NULL,
    [SupportEmail]        NVARCHAR (256)  NULL,
    [CurrencyID]          VARCHAR (3)     NULL,
    [BankingDetails]      NTEXT           NULL,
    [AccountManagerEmail] NVARCHAR (255)  NULL,
    [Website]             VARCHAR (255)   NULL
);

