/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


SET IDENTITY_INSERT [Retail].[Account] ON 

GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (1, N'Pakistan Fixed', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":false}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:12:12.553' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (2, N'Pakistan-Islamabad-Fixed', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":false}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:12:25.073' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (3, N'Pakistan-Karachi-Fixed', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":false}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:12:33.637' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (4, N'Pakistan-Lahore-Fixed', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":false}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:12:41.430' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (5, N'Pakistan Mobile_SCO', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:12:56.507' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (6, N'Pakistan-Mobilink-Mobile', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:13:07.450' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (7, N'Pakistan-Other-Mobile', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:13:17.207' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (8, N'Pakistan-Telenor-Mobile', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:13:29.310' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (9, N'Pakistan-Ufone-Mobile', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:13:38.830' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (10, N'Pakistan-Warid-Mobile', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:13:48.347' AS DateTime))
GO
INSERT [Retail].[Account] ([ID], [Name], [OldTypeID], [TypeID], [Settings], [ParentID], [StatusID], [SourceID], [ExecutedActionsData], [ExtendedSettings], [CreatedTime]) VALUES (11, N'Pakistan-Zong-Mobile', NULL, N'954557d8-c871-4636-9ec9-1677485543a9', N'{"$type":"Retail.BusinessEntity.Entities.AccountSettings, Retail.BusinessEntity.Entities","Parts":{"$type":"Retail.BusinessEntity.Entities.AccountPartCollection, Retail.BusinessEntity.Entities","83715d18-0db8-4af4-a9cd-e3ce321e71ad":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartCompanyProfile, Retail.BusinessEntity.MainExtensions","ConfigId":"b0717c4f-e409-4ae2-8c00-5add4ca828c5","Contacts":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Retail.BusinessEntity.MainExtensions.AccountParts.AccountCompanyContact, Retail.BusinessEntity.MainExtensions]], mscorlib"}}},"158359de-da10-409d-bf51-f0f23f6bea7d":{"$type":"Retail.BusinessEntity.Entities.AccountPart, Retail.BusinessEntity.Entities","Settings":{"$type":"Retail.BusinessEntity.MainExtensions.AccountParts.AccountPartOperatorSetting, Retail.BusinessEntity.MainExtensions","ConfigId":"a2f223cf-3570-4469-bfb6-4a918acf016b","IsMobileOperator":true}}}}', NULL, N'dadc2977-a348-4504-89c9-c92f8f9008dd', NULL, NULL, NULL, CAST(N'2017-06-23 11:14:01.913' AS DateTime))
GO

SET IDENTITY_INSERT [Retail].[Account] OFF


SET IDENTITY_INSERT [rules].[Rule] ON 

GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (1, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":true},"DefinitionId":"f67a1a52-e16e-4b81-839f-d5a2e2d70317","RuleId":1,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (2, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":false},"DefinitionId":"f67a1a52-e16e-4b81-839f-d5a2e2d70317","RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (3, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":1},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["92"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (4, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":2},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9251"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (5, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":3},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9221"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (6, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":4},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9242"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (7, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":5},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9235"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (8, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":6},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9230"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (9, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":7},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["923"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (10, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":8},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9234"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (11, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":9},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9233"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (12, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":10},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9232"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO
INSERT [rules].[Rule] ([ID], [TypeID], [RuleDetails], [BED], [EED], [SourceID]) VALUES (13, 4, N'{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRule, Vanrise.GenericData.Transformation.Entities","Settings":{"$type":"Vanrise.GenericData.Transformation.Entities.MappingRuleSettings, Vanrise.GenericData.Transformation.Entities","Value":11},"DefinitionId":"808a5c38-697d-4256-891e-a63005af3f01","Criteria":{"$type":"Vanrise.GenericData.Entities.GenericRuleCriteria, Vanrise.GenericData.Entities","FieldsValues":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Vanrise.GenericData.Entities.GenericRuleCriteriaFieldValues, Vanrise.GenericData.Entities]], mscorlib","NumberPrefix":{"$type":"Vanrise.GenericData.MainExtensions.GenericRuleCriteriaFieldValues.StaticValues, Vanrise.GenericData.MainExtensions","Values":{"$type":"System.Collections.Generic.List`1[[System.Object, mscorlib]], mscorlib","$values":["9231"]}}}},"RuleId":0,"BeginEffectiveTime":"2000-06-23T00:00:00","RefreshTimeSpan":"01:00:00"}', CAST(N'2000-06-23 00:00:00.000' AS DateTime), NULL, NULL)
GO

SET IDENTITY_INSERT [rules].[Rule] OFF