app.constant('WhS_BE_DBTableNameEnum', {
    Switch: { value: 0, description: "Switch", defaultMigrate: true },
    Currency: { value: 1, description: "Currency", defaultMigrate: true },
    CurrencyExchangeRate: { value: 2, description: "CurrencyExchangeRate", defaultMigrate: true },
    Country: { value: 3, description: "Country", defaultMigrate: true },
    CodeGroup: { value: 4, description: "CodeGroup", defaultMigrate: true },
    CarrierProfile: { value: 5, description: "CarrierProfile", defaultMigrate: true },
    CarrierAccount: { value: 6, description: "CarrierAccount", defaultMigrate: true },
    SaleZone: { value: 7, description: "SaleZone", defaultMigrate: true },
    SupplierZone: { value: 8, description: "SupplierZone", defaultMigrate: true },
    SaleCode: { value: 9, description: "SaleCode", defaultMigrate: true },
    SupplierCode: { value: 10, description: "SupplierCode", defaultMigrate: true },
    SupplierZoneService: { value: 11, description: "SupplierZoneService", defaultMigrate: true },
    SalePriceList: { value: 12, description: "SalePriceList", defaultMigrate: true },
    SupplierPriceList: { value: 13, description: "SupplierPriceList", defaultMigrate: true },
    SaleRate: { value: 14, description: "SaleRate", defaultMigrate: true },
    SupplierRate: { value: 15, description: "SupplierRate", defaultMigrate: true },
    CustomerZone: { value: 16, description: "CustomerZone", defaultMigrate: false },
    CustomerSellingProduct: { value: 17, description: "CustomerSellingProduct", defaultMigrate: false },
    File: { value: 18, description: "File", defaultMigrate: false },
    SwitchConnectivity: { value: 19, description: "SwitchConnectivity", defaultMigrate: true }
});
