app.constant('WhS_BE_SalePriceListTemplateSettingsCodeOnEachRowBEFieldEnum', {
    Zone: { value: 0, description: "Zone" },
    Code: { value: 1, description: "Code" },
    CodeBED: { value: 2, description: "Code BED" },
    CodeEED: { value: 3, description: "Rate&CodeEED (reflecting Last modification)" },
    Rate: { value: 4, description: "Rate" },
    RateBED: { value: 5, description: "Rate BED" },
    RateEED: { value: 6, description: "Rate EED" },
    Services: { value: 7, description: "Services" },
    RateChangeType: { value: 8, description: "Rate Change Type" },
    Currency: { value: 9, description: "Currency" },
    CodeChangeType: { value: 10, description: "Code Change Type" },
    Increment: { value: 11, description: "Increment" },
    CodeRateChangeType: { value: 12, description: "Code and Rate Change Type(reflecting Last modification)" },
    EffectiveDate: { value: 13, description: "Rate&CodeBED (reflecting Last modification)" },
    CodeGroup: { value: 14, description: "Code Group" },
    Country: { value: 15, description: "Country" },
    ZoneNameWithoutCountryName: { value: 16, description: "Zone Name Without Country Name" },
    AreaCode: { value: 17, description: "Area Code" },
});