
CREATE procedure [dbo].[prFill_out_trunkType] as


truncate table AN_Out_Trunk_type

 -------------- dawoodi switch----------------------------------------------
 
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES(' ' ,'null',5)
     
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'41BAB',5) 
     
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ABGRB',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ADMIA',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ALWIA',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'ASI2S',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'DH772',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'DORA1',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'DORA5',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ENTSR',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'GZ515',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'IN300',5)
      
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'JIHAD',5)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'KD515',5)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MAMN7',5)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MH546',5)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'N7555',5)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'N7BAY',5)
     
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'N7BG1',5)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'N7BOR',5)
    
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('INT' ,'N7JAD',5)
     
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NSROG',5)
     
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SALAM',5)
     
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SALHI',5)
     
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SINK',5)
            
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SALAM',5)
            
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'WLL',5)
     
    
     
  -------------------------------Dobbat SWitch-----   
  
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'NULL',3)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'AM043',3)
       
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'ASIS1',3)
       
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'BA025',3)
       
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'BA044',3)
       
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'BA046',3)
       
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'DI036',3)
            
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'HI030',3)
  
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'IMSDB',3)
      
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KA032',3)
      
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KI050',3)
      
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KU023',3)
      
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MO607',3)
     
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MO608',3)
  
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NA033',3)
  
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NA042',3)
  
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'R2KAL',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'RA024',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7443',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7444',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7555',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7556',3)
          
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7771',3)
          
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7775',3)
          
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7ADM',3)
          
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7ALW',3)
          
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7AMN',3)
          
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7BYA',3)
     
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'S7CL4',3)
         
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7CL5',3)
         
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7DAD',3)
         
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7ENT',3)
         
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7GAZ',3)
         
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7HSL',3)
            
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'S7IN',3)
     
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7JAD',3)
            
              INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7JHD',3)
            
              INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7JUL',3)
            
              INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7KDH',3)
            
              INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7MDH',3)
            
              INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7QTL',3)
            
              INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7RAS',3)
     
             INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7SAL',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7SNK',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'S7ZAF',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'S7WLL',3)
     
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'SE037',3)
     
     
  
  
------------------------Alcatel Basrah Switch-----------------------------
 
   
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'NULL',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ALCN7',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'AMQN7',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'AND41',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ANDN7',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'ASIN7',4) 
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'BABN7',4)
  
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('DATA' ,'DATR2',4)
      
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('DATA' ,'DERN7',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'DHBN7',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('POL' ,'EMRN7',4)
     
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'ERCN7',4)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'ERCR2',4)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'HLAN7',4)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HWRN7',4)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'JADN7',4)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KUTN7',4)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MAMN7',4)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MASN7',4)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MDNN7',4)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NAJN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NASN7',5)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'OMNN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'QRUN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'SAMN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'TANN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'UMGN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ZBRN7',4)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ZTEN7',4)

     
     ------------------------------Diwaniya SWitch---------------------------
    
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'AFAN7',6)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ALBD2',6)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ALCN7',6)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'ASHN7',6)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'DAGR2',6)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('INT' ,'ERCGW',6)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'GHDN7',6)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'GHMR2',6)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'HILN7',6)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'HMZN7',6)
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'INN7',6)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KRBN7',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MOSN7',6)
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MHNR2',6)
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KUTN7',6)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MUSN7',6)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NAJN7',6)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NASN7',6)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NGN7',6)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NUFN7',6)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SALR2',6)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'NULL',6)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'SAMN7',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SEDN7',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SHAM7',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SHFN7',6)
             INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SHNR2',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SNEN7',6)
       
               INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SUMR2',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'THDN7',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('INT' ,'ZANGW',6)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ZWRN7',6)
       
       
       
       -----------------------------Karbala Switch----------------------
       
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'NULL',9)  
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'AINN7',9)  
             INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ALCN7',9)  
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'DYNN7',9)  
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HAHN7',9)  
           INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HAWN7',9)  
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'HILN7',9)  
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HINN7',9)  
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HINR2',9)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HORN7',9)  
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'INN7',9)  
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('INT' ,'JADN7',9) 
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'JDWR2',9) 
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'KAIR2',9)
      
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KUTN7',9) 

    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MOMN7',9) 
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NAJN7',9) 
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NASN7',9) 
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'OMNN7',9) 
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SLON7',9)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'SMON7',9) 
     
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'ZAYN7',9) 
      INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ZTN7',9) 
     
 
-----------------------------Hilla Switch----------------------------------    
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('' ,'NULL',1) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
  VALUES('LCL' ,'AG7',1) 
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'AGBW',1)     
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('INT' ,'BG7',1)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'BRA7',1)
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'BSRK7',1)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'DAK7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'DY7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'EM7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'EMBW',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HS7',1)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HSBW',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'IN7',1)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'JBL7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'JUR7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'JURBW',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'KFL7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KOT7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KR7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'KRINT',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MAN7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MANGN',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MAT7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MH7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MHBW',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MS7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MSL7',1)    
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NAJ7',1)   
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NEL7',1)    
    INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NELBW',1)   
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NGN7',1)     
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NSR7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'OMN7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'OMN76',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'QM7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'QMBW',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SCN7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SD7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SDBW',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SHO7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SLOV6',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'SLOV8',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'SMC7',1)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'TAL7',1)

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'THB7',1)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'WLL7',1)
     
     

--------------------------------Nasria Switch------------------------------------------

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('' ,'NULL',2) 

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'AAMR7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'AKEKA',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'BASRA',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'BATH2',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'BATHA',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'CHBS7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'DABAT',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'DKEL7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'DWAY7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'DWN',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'ESLH7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'ESLH7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'ESLH7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'FDAL7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'FHOD7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'FJER7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('INT' ,'GADR',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'GHRF7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'HILLA',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'HMAR',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('IN' ,'IN',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'KRBLA',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'KRMA7',2) 
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'MAMON',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'MANR7',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('IN' ,'NASER',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('IN' ,'NET',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('' ,'NGN1',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'NJF',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'QLAH7',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'RFAY7',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'SDNWA',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'SHADA',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'SHTR7',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('TRS' ,'SMW',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'SUQ7',2)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
VALUES('LCL' ,'TAR',2)
 


-----------------------------------Najaf Switch-----------------------------------------
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'NULL',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'3GM',7)

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ABASM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'ASHAM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'ATHRM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'ATHRS',7)

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('DAT' ,'DATAM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'DEWAM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HADM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HERAM',7)

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'HILLM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'HURM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'INM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'INM2',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'JADRM',7)

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KARBM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'KARNA',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'KUTM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'MAMOM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MESAM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MGWM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MISH2',7)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MISHM',7)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MNAM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'MNAR',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NAASM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'NSRM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'NYN1M',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'OMN7',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'OMNES',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('POL' ,'POLIM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'QADSM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'QADSR',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'SMAWM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'WAFAM',7)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ZTEM',7)

-------------------------------Maamoun Switch----------------------


INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'406',8)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'410',8)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'424',8)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'433',8)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'438',8)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'442',8)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'460',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'461',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'500',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'528',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'532',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'540',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'546',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'573',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'578',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'582',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'587',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'596',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'644',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('GOV' ,'646',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'648',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'673',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'717',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'726',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'762',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'2c6',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'3f2',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'3fc',8)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'41a',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'42e',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'4b0',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'4ba',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'4c4',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'4ce',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'4d8',8)
        INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'4ec',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'53c',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'54b',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'55a',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'5a5',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'5aa',8)
            INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'5bb',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'67c',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'6b8',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'6cc',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'6eb',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'71d',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'78a',8)
          INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'7b2',8)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'7bc',8)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'7c6',8)
         INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'7da',8)
    
    
    -----------------------------------Jadriya Switch---------------
    
    
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('INT' ,'00000',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00001',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00002',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00003',10)    
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00004',10) 
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00005',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00006',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00007',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00008',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00009',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00010',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00011',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00012',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00015',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00016',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00017',10)
   INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00018',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00019',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00020',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00021',10)
  INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00022',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00023',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00024',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00026',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00027',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00028',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00029',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00030',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00032',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00033',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00034',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00035',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'00038',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00039',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'00040',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('IN' ,'00041',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'00042',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00043',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00044',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00046',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00049',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00050',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('GOV' ,'00051',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00052',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00055',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'00058',10)
 INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00070',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00072',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00073',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00074',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00101',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00103',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00105',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00106',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00108',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00109',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00114',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00115',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00116',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'00118',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('GOV' ,'00120',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'00122',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00125',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00130',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('DATA' ,'00135',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('GOV' ,'00141',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'00144',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('DATA' ,'00145',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('TRS' ,'00147',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'00500',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'00501',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MOB' ,'00503',10)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('WLL' ,'00504',10)


------------------Samawah SWitch--------------------------------------------------------

INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'NULL',11)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ASKN7',11)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('' ,'EICM',11)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('MIX' ,'ERIN7',11)
INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'KDRN7',11)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'RAMN7',11)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'RSALA',11)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'RMETH',11)
     INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'YRMN7',11)
       INSERT INTO [CDRAnalysis].[dbo].[AN_Out_Trunk_type]  ([out_type] ,[out_trunk] ,[SwitchId])
     VALUES('LCL' ,'ZTE',11)