app.constant('BillingCDRMeasureEnum', {
    //Switch: { value: 0, propertyName: "SwitchID", description: "Switch" },
    //CustomerZone: { value: 1, propertyName: "CustomerZone", description: "Customer Zone" },
    ////Attempts: { value: 2, propertyName: "Attempts", description: "Attempts" },
    //OriginatingZone: { value: 3, propertyName: "OriginatingZoneID", description: "Originating Zone" },
    //CallDate: { value: 5, propertyName: "CallDate", description: "CallDate" },
    //Customer: { value: 4, propertyName: "CustomerID", description: "Customer" },
    //CLI: { value: 6, propertyName: "CLI", description: "CLI" },
    //PDD: { value: 7, propertyName: "PDDInSeconds", description: "PDD (sec)" },
    //Number: { value: 8, propertyName: "Number", description: "Number" },
    //NumberOfCalls: { value: 9, propertyName: "NumberOfCalls", description: "Nb of Calls", isSum: true },
    //DeliveredNumberOfCalls: { value: 10, propertyName: "DeliveredNumberOfCalls", description: "Delivered Nb of Calls", isSum: true },
    //PGAD: { value: 11, propertyName: "PGAD", description: "PGAD" }
    SwitchName: { value: 0, propertyName: "SwitchName", description: "SwitchName" },
    OurZoneName: { value: 8, propertyName: "OurZoneName", description: "OurZoneName" },
    CustomerInfo: { value: 1, propertyName: "CustomerInfo", description: "CustomerInfo" },
    Attempt: { value: 2, propertyName: "Attempt", description: "Attempt" },
    Alert: { value: 3, propertyName: "Alert", description: "Alert" },
    Connect: { value: 4, propertyName: "Connect", description: "Connect" },
    Disconnect: { value: 5, propertyName: "Disconnect", description: "Disconnect" },
    DurationInSeconds: { value: 6, propertyName: "DurationInSeconds", description: "DurationInSeconds" },
    OriginatingZoneID: { value: 9, propertyName: "OriginatingZoneID", description: "OriginatingZoneID" },
    SupplierID: { value:10, propertyName: "SupplierID", description: "SupplierID" },
    SupplierZoneID: { value: 11, propertyName: "SupplierZoneID", description: "SupplierZoneID" },
    CDPN: { value: 12, propertyName: "CDPN", description: "CDPN" }
});