app.constant('RawCDRLogMeasureEnum', {
    CDRID: { value: 0, propertyName: "CDRID", description: "CDR ID", type: "Text" },
    SwitchName: { value: 1, propertyName: "SwitchName", description: "SwitchName", type: "Text" },
    IDonSwitch: { value: 2, propertyName: "IDonSwitch", description: "IDonSwitch", type: "Text" },
    Tag: { value: 3, propertyName: "Tag", description: "Tag", type: "DateTime" },
    AttemptDateTime: { value: 4, propertyName: "AttemptDateTime", description: "AttemptDateTime", type: "Text" },
    AlertDateTime: { value: 5, propertyName: "AlertDateTime", description: "AlertDateTime", type: "Text" },
    ConnectDateTime: { value: 6, propertyName: "ConnectDateTime", description: "ConnectDateTime", type: "Number" },
    DisconnectDateTime: { value: 7, propertyName: "DisconnectDateTime", description: "DisconnectDateTime", type: "Text" },
    DurationInSeconds: { value: 8, propertyName: "DurationInSeconds", description: "DurationInSeconds", type: "Text" },
    IN_TRUNK: { value: 9, propertyName: "IN_TRUNK", description: "IN TRUNK", type: "Number" },
    IN_CIRCUIT: { value: 10, propertyName: "IN_CIRCUIT", description: "IN CIRCUIT", type: "Text" },
    IN_CARRIER: { value: 11, propertyName: "IN_CARRIER", description: "IN CARRIER", type: "Text" },
    IN_IP: { value: 12, propertyName: "IN_IP", description: "IN IP", type: "Text" },
    OUT_TRUNK: { value: 13, propertyName: "OUT_TRUNK", description: "OUT TRUNK", type: "Text" },
    OUT_CIRCUIT: { value: 14, propertyName: "OUT_CIRCUIT", description: "OUT CIRCUIT", type: "Text" },
    OUT_CARRIER: { value: 15, propertyName: "OUT_CARRIER", description: "OUT CARRIER", type: "Text" },
    OUT_IP: { value: 16, propertyName: "OUT_IP", description: "OUT IP", type: "Text" },
    CGPN: { value: 17, propertyName: "CGPN", description: "CGPN", type: "Text" },
    CDPN: { value: 18, propertyName: "CDPN", description: "CDPN", type: "Text" },
    CDPNOut: { value: 19, propertyName: "CDPNOut", description: "CDPNOut", type: "Text" },
    CAUSE_FROM_RELEASE_CODE: { value: 20, propertyName: "CAUSE_FROM_RELEASE_CODE", description: "CAUSE FROM RELEASE CODE", type: "Text" },
    CAUSE_FROM: { value: 21, propertyName: "CAUSE_FROM", description: "CAUSE FROM", type: "Text" },
    CAUSE_TO_RELEASE_CODE: { value: 22, propertyName: "CAUSE_TO_RELEASE_CODE", description: "CAUSE TO RELEASE CODE", type: "Text" },
    CAUSE_TO: { value: 23, propertyName: "CAUSE_TO", description: "CAUSE TO", type: "Text" },
    IsRerouted: { value: 24, propertyName: "IsRerouted", description: "IsRerouted", type: "Text" },
    Extra_Fields: { value: 25, propertyName: "Extra_Fields", description: "Extra Fields", type: "Text" },

});