//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallServiceClient.Service1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestMethodInput", Namespace="http://schemas.datacontract.org/2004/07/WebApplication2")]
    [System.SerializableAttribute()]
    public partial class TestMethodInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestMethodOutput", Namespace="http://schemas.datacontract.org/2004/07/WebApplication2")]
    [System.SerializableAttribute()]
    public partial class TestMethodOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Text1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Text2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text1 {
            get {
                return this.Text1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Text1Field, value) != true)) {
                    this.Text1Field = value;
                    this.RaisePropertyChanged("Text1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text2 {
            get {
                return this.Text2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Text2Field, value) != true)) {
                    this.Text2Field = value;
                    this.RaisePropertyChanged("Text2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vanrise.bp.services", ConfigurationName="Service1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vanrise.bp.services/IService1/DoWork", ReplyAction="http://vanrise.bp.services/IService1/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vanrise.bp.services/IService1/DoWork", ReplyAction="http://vanrise.bp.services/IService1/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vanrise.bp.services/IService1/TestMethod2", ReplyAction="http://vanrise.bp.services/IService1/TestMethod2Response")]
        CallServiceClient.Service1.TestMethodOutput TestMethod2(CallServiceClient.Service1.TestMethodInput input, CallServiceClient.Service1.TestMethodInput input2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vanrise.bp.services/IService1/TestMethod2", ReplyAction="http://vanrise.bp.services/IService1/TestMethod2Response")]
        System.Threading.Tasks.Task<CallServiceClient.Service1.TestMethodOutput> TestMethod2Async(CallServiceClient.Service1.TestMethodInput input, CallServiceClient.Service1.TestMethodInput input2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CallServiceClient.Service1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CallServiceClient.Service1.IService1>, CallServiceClient.Service1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public CallServiceClient.Service1.TestMethodOutput TestMethod2(CallServiceClient.Service1.TestMethodInput input, CallServiceClient.Service1.TestMethodInput input2) {
            return base.Channel.TestMethod2(input, input2);
        }
        
        public System.Threading.Tasks.Task<CallServiceClient.Service1.TestMethodOutput> TestMethod2Async(CallServiceClient.Service1.TestMethodInput input, CallServiceClient.Service1.TestMethodInput input2) {
            return base.Channel.TestMethod2Async(input, input2);
        }
    }
}
