CREATE TABLE [dbo].[SIMBOX_CDRS2] (
    [STARTTIME]         VARCHAR (50) NULL,
    [SERVEDIMSI]        VARCHAR (50) NULL,
    [SERVEDIMEI]        VARCHAR (50) NULL,
    [SERVEDMSISDN]      VARCHAR (50) NULL,
    [FIRSTCELLID]       VARCHAR (50) NULL,
    [SERVEDOTHERNUMBER] VARCHAR (50) NULL,
    [CALLDURATION]      VARCHAR (50) NULL
);

