//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.CDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalizedCDR
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ConnectDateTime { get; set; }
        public Nullable<System.DateTime> DisconnectDateTime { get; set; }
        public Nullable<decimal> DurationInSeconds { get; set; }
        public string In_Trunk { get; set; }
        public string Out_Trunk { get; set; }
        public string In_Type { get; set; }
        public string Out_Type { get; set; }
        public string A_Temp { get; set; }
        public string B_Temp { get; set; }
        public string Switch { get; set; }
        public Nullable<int> IsRepeated { get; set; }
        public Nullable<int> SwitchId { get; set; }
        public Nullable<int> CDRId { get; set; }
    }
}
