//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.CDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.CDRs = new HashSet<CDR>();
            this.SourceMappings = new HashSet<SourceMapping>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> SourceKindID { get; set; }
        public Nullable<int> SwitchID { get; set; }
    
        public virtual ICollection<CDR> CDRs { get; set; }
        public virtual SourceKind SourceKind { get; set; }
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
        public virtual SwitchProfile SwitchProfile { get; set; }
    }
}
