//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.CDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class To_be_deleted_CookedCDR
    {
        public long ID { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> ConnectDateTime { get; set; }
        public Nullable<System.DateTime> DisconnectDateTime { get; set; }
        public Nullable<decimal> DurationInSeconds { get; set; }
        public string IN_TRUNK { get; set; }
        public string IN_CARRIER { get; set; }
        public string OUT_TRUNK { get; set; }
        public string OUT_CARRIER { get; set; }
        public string CGPN { get; set; }
        public string CDPN { get; set; }
        public string Extra_Fields { get; set; }
        public string IsRerouted { get; set; }
        public string CDPNOut { get; set; }
        public Nullable<System.DateTime> AttemptDateTime { get; set; }
        public Nullable<System.DateTime> AlertDateTime { get; set; }
        public Nullable<short> IN_CIRCUIT { get; set; }
        public string IN_IP { get; set; }
        public Nullable<short> OUT_CIRCUIT { get; set; }
        public string OUT_IP { get; set; }
        public string CAUSE_FROM_RELEASE_CODE { get; set; }
        public string CAUSE_FROM { get; set; }
        public string CAUSE_TO_RELEASE_CODE { get; set; }
        public string CAUSE_TO { get; set; }
        public string SIP { get; set; }
        public string in_type { get; set; }
        public string out_type { get; set; }
        public string A_temp { get; set; }
        public string B_temp { get; set; }
        public Nullable<int> IGNORE { get; set; }
        public string @switch { get; set; }
    }
}
