//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasesLog
    {
        public int ID { get; set; }
        public int ChangeTypeID { get; set; }
        public Nullable<int> ReportingStatusID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> MobileOperatorFeedbackID { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int GeneratedCallID { get; set; }
    
        public virtual ChangeType ChangeType { get; set; }
        public virtual MobileOperatorFeedback MobileOperatorFeedback { get; set; }
        public virtual ReportingStatus ReportingStatus { get; set; }
        public virtual Status Status { get; set; }
    }
}
