//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class delete_ViewSourceGenerates
    {
        public long Row { get; set; }
        public Nullable<int> CountGenerated { get; set; }
        public Nullable<System.DateTime> attemptdate { get; set; }
        public string Name { get; set; }
    }
}
