//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailCC
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<int> MobileOperatorID { get; set; }
        public int ClientID { get; set; }
    
        public virtual MobileOperator MobileOperator { get; set; }
        public virtual Client Client { get; set; }
    }
}
