//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int ID { get; set; }
        public string SenderName { get; set; }
        public string SenderMail { get; set; }
        public string DestinationName { get; set; }
        public string DestinationEmail { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string EmailFormat { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> EmailTemplateID { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}
