//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionType> ActionTypes { get; set; }
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public DbSet<AppType> AppTypes { get; set; }
        public DbSet<Carrier> Carriers { get; set; }
        public DbSet<CasesLog> CasesLogs { get; set; }
        public DbSet<ChangeType> ChangeTypes { get; set; }
        public DbSet<EmailCC> EmailCCs { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<EmailToken> EmailTokens { get; set; }
        public DbSet<GMT> GMTs { get; set; }
        public DbSet<Import> Imports { get; set; }
        public DbSet<ImportType> ImportTypes { get; set; }
        public DbSet<LoggedAction> LoggedActions { get; set; }
        public DbSet<MobileOperatorFeedback> MobileOperatorFeedbacks { get; set; }
        public DbSet<MobileOperator> MobileOperators { get; set; }
        public DbSet<OriginationNetwork> OriginationNetworks { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<PredefinedColumn> PredefinedColumns { get; set; }
        public DbSet<PredefinedColumnsforRelatedNumber> PredefinedColumnsforRelatedNumbers { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<RecievedCall> RecievedCalls { get; set; }
        public DbSet<RecievedEmail> RecievedEmails { get; set; }
        public DbSet<RecommendedAction> RecommendedActions { get; set; }
        public DbSet<RelatedNumberMapping> RelatedNumberMappings { get; set; }
        public DbSet<RelatedNumber> RelatedNumbers { get; set; }
        public DbSet<ReportingStatus> ReportingStatuses { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<SourceKind> SourceKinds { get; set; }
        public DbSet<SourceMapping> SourceMappings { get; set; }
        public DbSet<Source> Sources { get; set; }
        public DbSet<SourceType> SourceTypes { get; set; }
        public DbSet<Status> Statuses { get; set; }
        public DbSet<SwitchProfile> SwitchProfiles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<SysParameter> SysParameters { get; set; }
        public DbSet<ToneFeedback> ToneFeedbacks { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ValueType> ValueTypes { get; set; }
        public DbSet<WebsiteMenu> WebsiteMenus { get; set; }
        public DbSet<View_Origination> View_Origination { get; set; }
        public DbSet<ViewSummary> ViewSummaries { get; set; }
        public DbSet<vwAllCase> vwAllCases { get; set; }
        public DbSet<vwCLI> vwCLIs { get; set; }
        public DbSet<vwCount> vwCounts { get; set; }
        public DbSet<vwFraudCase> vwFraudCases { get; set; }
        public DbSet<vwRepeatedCase> vwRepeatedCases { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<GeneratedCall> GeneratedCalls { get; set; }
        public DbSet<ViewGeneratedCall> ViewGeneratedCalls { get; set; }
        public DbSet<ViewGeneratedCallsNew> ViewGeneratedCallsNews { get; set; }
    
        public virtual int delete_asp_Write_String_To_File(string @string, string path, string filename)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var pathParameter = path != null ?
                new ObjectParameter("Path", path) :
                new ObjectParameter("Path", typeof(string));
    
            var filenameParameter = filename != null ?
                new ObjectParameter("Filename", filename) :
                new ObjectParameter("Filename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_asp_Write_String_To_File", stringParameter, pathParameter, filenameParameter);
        }
    
        public virtual int delete_ConvertTableToHtml(string sqlQuery, ObjectParameter html)
        {
            var sqlQueryParameter = sqlQuery != null ?
                new ObjectParameter("SqlQuery", sqlQuery) :
                new ObjectParameter("SqlQuery", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_ConvertTableToHtml", sqlQueryParameter, html);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_prCountDistinctFraudCases(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, ObjectParameter count, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_prCountDistinctFraudCases", mobileOperatorIDParameter, startDateParameter, endDateParameter, count, clientIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_prCountFraudCases(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, ObjectParameter count, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_prCountFraudCases", mobileOperatorIDParameter, startDateParameter, endDateParameter, count, clientIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_prCountGeneratedCases(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, ObjectParameter count, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_prCountGeneratedCases", mobileOperatorIDParameter, startDateParameter, endDateParameter, count, clientIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> delete_prCountOnnetFraudCases(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, ObjectParameter count, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("delete_prCountOnnetFraudCases", mobileOperatorIDParameter, startDateParameter, endDateParameter, count, clientIDParameter);
        }
    
        public virtual int delete_prGetAllCasesofMobileOperator(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_prGetAllCasesofMobileOperator", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual int delete_prGetAllCasesofMobileOperator_Admin(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_prGetAllCasesofMobileOperator_Admin", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual int delete_prGetFraudCasesofMobileOperator(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_prGetFraudCasesofMobileOperator", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual int delete_prGetFraudCasesofMobileOperator_Admin(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_prGetFraudCasesofMobileOperator_Admin", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<delete_prSummary_Admin_Result> delete_prSummary_Admin(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID, Nullable<int> mobileOperatorID)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<delete_prSummary_Admin_Result>("delete_prSummary_Admin", startDateParameter, endDateParameter, clientIDParameter, mobileOperatorIDParameter);
        }
    
        public virtual ObjectResult<delete_prViewCarrier_Result> delete_prViewCarrier(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<delete_prViewCarrier_Result>("delete_prViewCarrier", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<delete_prViewCarrier_Admin_Result> delete_prViewCarrier_Admin(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<delete_prViewCarrier_Admin_Result>("delete_prViewCarrier_Admin", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<delete_prViewOrigination_Admin_Result> delete_prViewOrigination_Admin(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<delete_prViewOrigination_Admin_Result>("delete_prViewOrigination_Admin", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prCaseStatuses_Result> prCaseStatuses(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prCaseStatuses_Result>("prCaseStatuses", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<prClientCases_Result> prClientCases(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prClientCases_Result>("prClientCases", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<prComparisons_Result> prComparisons(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prComparisons_Result>("prComparisons", startDateParameter, endDateParameter);
        }
    
        public virtual int prDeleteEmail(string ids)
        {
            var idsParameter = ids != null ?
                new ObjectParameter("Ids", ids) :
                new ObjectParameter("Ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prDeleteEmail", idsParameter);
        }
    
        public virtual int prGetAllCases(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID, Nullable<bool> isAdmin)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetAllCases", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter, isAdminParameter);
        }
    
        public virtual int prGetAllCases_LoadonDemand(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID, Nullable<bool> isAdmin, Nullable<int> pageIndex, Nullable<int> pageSize, Nullable<bool> onlyCount)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var onlyCountParameter = onlyCount.HasValue ?
                new ObjectParameter("OnlyCount", onlyCount) :
                new ObjectParameter("OnlyCount", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetAllCases_LoadonDemand", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter, isAdminParameter, pageIndexParameter, pageSizeParameter, onlyCountParameter);
        }
    
        public virtual ObjectResult<prGetEmails_Result> prGetEmails(string destinationEmail, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var destinationEmailParameter = destinationEmail != null ?
                new ObjectParameter("DestinationEmail", destinationEmail) :
                new ObjectParameter("DestinationEmail", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetEmails_Result>("prGetEmails", destinationEmailParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual int prGetFraudCases(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID, Nullable<int> onnetorOffnet, Nullable<bool> isAdmin)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var onnetorOffnetParameter = onnetorOffnet.HasValue ?
                new ObjectParameter("OnnetorOffnet", onnetorOffnet) :
                new ObjectParameter("OnnetorOffnet", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetFraudCases", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter, onnetorOffnetParameter, isAdminParameter);
        }
    
        public virtual int prGetFraudCases_LoadonDemand(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID, Nullable<int> onnetorOffnet, Nullable<bool> isAdmin, Nullable<int> pageIndex, Nullable<int> pageSize, Nullable<bool> onlyCount)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var onnetorOffnetParameter = onnetorOffnet.HasValue ?
                new ObjectParameter("OnnetorOffnet", onnetorOffnet) :
                new ObjectParameter("OnnetorOffnet", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var onlyCountParameter = onlyCount.HasValue ?
                new ObjectParameter("OnlyCount", onlyCount) :
                new ObjectParameter("OnlyCount", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetFraudCases_LoadonDemand", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter, onnetorOffnetParameter, isAdminParameter, pageIndexParameter, pageSizeParameter, onlyCountParameter);
        }
    
        public virtual int prGetRepeatedCases(Nullable<int> mobileOperatorID, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prGetRepeatedCases", mobileOperatorIDParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prGetSummaryClient_Result> prGetSummaryClient(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetSummaryClient_Result>("prGetSummaryClient", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prGetTimeActiveonNetwork_Result> prGetTimeActiveonNetwork(Nullable<int> mobileOperatorID, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetTimeActiveonNetwork_Result>("prGetTimeActiveonNetwork", mobileOperatorIDParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prGetToBeReported_Result> prGetToBeReported(Nullable<int> mobileOperatorID, Nullable<int> receivedMobileOperatorID, Nullable<int> sourceID, Nullable<int> receivedSourceID, Nullable<int> statusID, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var receivedMobileOperatorIDParameter = receivedMobileOperatorID.HasValue ?
                new ObjectParameter("ReceivedMobileOperatorID", receivedMobileOperatorID) :
                new ObjectParameter("ReceivedMobileOperatorID", typeof(int));
    
            var sourceIDParameter = sourceID.HasValue ?
                new ObjectParameter("SourceID", sourceID) :
                new ObjectParameter("SourceID", typeof(int));
    
            var receivedSourceIDParameter = receivedSourceID.HasValue ?
                new ObjectParameter("ReceivedSourceID", receivedSourceID) :
                new ObjectParameter("ReceivedSourceID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetToBeReported_Result>("prGetToBeReported", mobileOperatorIDParameter, receivedMobileOperatorIDParameter, sourceIDParameter, receivedSourceIDParameter, statusIDParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prImports_Result> prImports(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prImports_Result>("prImports", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<prLastImports_Result> prLastImports()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prLastImports_Result>("prLastImports");
        }
    
        public virtual int prLevelOneCompare()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prLevelOneCompare");
        }
    
        public virtual int prLevelOneCompare_HaveNoGenerated(Nullable<System.DateTime> levelOneComparisonDateTime)
        {
            var levelOneComparisonDateTimeParameter = levelOneComparisonDateTime.HasValue ?
                new ObjectParameter("LevelOneComparisonDateTime", levelOneComparisonDateTime) :
                new ObjectParameter("LevelOneComparisonDateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prLevelOneCompare_HaveNoGenerated", levelOneComparisonDateTimeParameter);
        }
    
        public virtual int prLevelOneCompare_HaveNoGenerated_Android(Nullable<System.DateTime> levelOneComparisonDateTime)
        {
            var levelOneComparisonDateTimeParameter = levelOneComparisonDateTime.HasValue ?
                new ObjectParameter("LevelOneComparisonDateTime", levelOneComparisonDateTime) :
                new ObjectParameter("LevelOneComparisonDateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prLevelOneCompare_HaveNoGenerated_Android", levelOneComparisonDateTimeParameter);
        }
    
        public virtual ObjectResult<prReports_Result> prReports(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prReports_Result>("prReports", startDateParameter, endDateParameter);
        }
    
        public virtual int prSendMail(string profile_name, string recipients, string subject, string copy_recipients, string body)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prSendMail", profile_nameParameter, recipientsParameter, subjectParameter, copy_recipientsParameter, bodyParameter);
        }
    
        public virtual int prSendMailWithAttachment(string profile_name, string recipients, string subject, string copy_recipients, string body, string file_attachments)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var file_attachmentsParameter = file_attachments != null ?
                new ObjectParameter("file_attachments", file_attachments) :
                new ObjectParameter("file_attachments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prSendMailWithAttachment", profile_nameParameter, recipientsParameter, subjectParameter, copy_recipientsParameter, bodyParameter, file_attachmentsParameter);
        }
    
        public virtual ObjectResult<prSourceGenerates_Result> prSourceGenerates(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prSourceGenerates_Result>("prSourceGenerates", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<prSourceGeneratesRecieves_Result> prSourceGeneratesRecieves(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prSourceGeneratesRecieves_Result>("prSourceGeneratesRecieves", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<prSourceRecieves_Result> prSourceRecieves(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prSourceRecieves_Result>("prSourceRecieves", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<prSummary_Result> prSummary(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prSummary_Result>("prSummary", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prViewOrigination_Result> prViewOrigination(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prViewOrigination_Result>("prViewOrigination", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prVwCarrier_Result> prVwCarrier(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID, Nullable<bool> isAdmin)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prVwCarrier_Result>("prVwCarrier", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<prVwOrigination_Result> prVwOrigination(Nullable<int> mobileOperatorID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> clientID, Nullable<bool> isAdmin)
        {
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prVwOrigination_Result>("prVwOrigination", mobileOperatorIDParameter, startDateParameter, endDateParameter, clientIDParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<SaveMail_Result> SaveMail(string profile_name, string recipients, string subject, string body, string copy_recipients, Nullable<int> emailTemplateId)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var emailTemplateIdParameter = emailTemplateId.HasValue ?
                new ObjectParameter("EmailTemplateId", emailTemplateId) :
                new ObjectParameter("EmailTemplateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveMail_Result>("SaveMail", profile_nameParameter, recipientsParameter, subjectParameter, bodyParameter, copy_recipientsParameter, emailTemplateIdParameter);
        }
    
        public virtual ObjectResult<SaveMailWithAttachement_Result> SaveMailWithAttachement(string profile_name, string recipients, string subject, string body, Nullable<int> emailTemplateId, string copy_recipients, string file_attachments)
        {
            var profile_nameParameter = profile_name != null ?
                new ObjectParameter("profile_name", profile_name) :
                new ObjectParameter("profile_name", typeof(string));
    
            var recipientsParameter = recipients != null ?
                new ObjectParameter("recipients", recipients) :
                new ObjectParameter("recipients", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var emailTemplateIdParameter = emailTemplateId.HasValue ?
                new ObjectParameter("EmailTemplateId", emailTemplateId) :
                new ObjectParameter("EmailTemplateId", typeof(int));
    
            var copy_recipientsParameter = copy_recipients != null ?
                new ObjectParameter("copy_recipients", copy_recipients) :
                new ObjectParameter("copy_recipients", typeof(string));
    
            var file_attachmentsParameter = file_attachments != null ?
                new ObjectParameter("file_attachments", file_attachments) :
                new ObjectParameter("file_attachments", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SaveMailWithAttachement_Result>("SaveMailWithAttachement", profile_nameParameter, recipientsParameter, subjectParameter, bodyParameter, emailTemplateIdParameter, copy_recipientsParameter, file_attachmentsParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int prFzeroCases(string caseID, Nullable<int> sourceID, Nullable<int> receivedSourceID, Nullable<int> mobileOperatorID, Nullable<int> statusID, Nullable<int> priorityID, Nullable<int> reportingStatusID, string a_number, string b_number, string cLI, string originationNetwork, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID, Nullable<int> cliReported)
        {
            var caseIDParameter = caseID != null ?
                new ObjectParameter("CaseID", caseID) :
                new ObjectParameter("CaseID", typeof(string));
    
            var sourceIDParameter = sourceID.HasValue ?
                new ObjectParameter("SourceID", sourceID) :
                new ObjectParameter("SourceID", typeof(int));
    
            var receivedSourceIDParameter = receivedSourceID.HasValue ?
                new ObjectParameter("ReceivedSourceID", receivedSourceID) :
                new ObjectParameter("ReceivedSourceID", typeof(int));
    
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var priorityIDParameter = priorityID.HasValue ?
                new ObjectParameter("PriorityID", priorityID) :
                new ObjectParameter("PriorityID", typeof(int));
    
            var reportingStatusIDParameter = reportingStatusID.HasValue ?
                new ObjectParameter("ReportingStatusID", reportingStatusID) :
                new ObjectParameter("ReportingStatusID", typeof(int));
    
            var a_numberParameter = a_number != null ?
                new ObjectParameter("a_number", a_number) :
                new ObjectParameter("a_number", typeof(string));
    
            var b_numberParameter = b_number != null ?
                new ObjectParameter("b_number", b_number) :
                new ObjectParameter("b_number", typeof(string));
    
            var cLIParameter = cLI != null ?
                new ObjectParameter("CLI", cLI) :
                new ObjectParameter("CLI", typeof(string));
    
            var originationNetworkParameter = originationNetwork != null ?
                new ObjectParameter("OriginationNetwork", originationNetwork) :
                new ObjectParameter("OriginationNetwork", typeof(string));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var cliReportedParameter = cliReported.HasValue ?
                new ObjectParameter("CliReported", cliReported) :
                new ObjectParameter("CliReported", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prFzeroCases", caseIDParameter, sourceIDParameter, receivedSourceIDParameter, mobileOperatorIDParameter, statusIDParameter, priorityIDParameter, reportingStatusIDParameter, a_numberParameter, b_numberParameter, cLIParameter, originationNetworkParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter, cliReportedParameter);
        }
    
        public virtual ObjectResult<prResultingCases_Result> prResultingCases(string caseID, Nullable<int> sourceID, Nullable<int> receivedSourceID, Nullable<int> mobileOperatorID, Nullable<int> statusID, Nullable<int> priorityID, Nullable<int> reportingStatusID, string a_number, string b_number, string cLI, string originationNetwork, Nullable<System.DateTime> fromAttemptDateTime, Nullable<System.DateTime> toAttemptDateTime, Nullable<int> clientID)
        {
            var caseIDParameter = caseID != null ?
                new ObjectParameter("CaseID", caseID) :
                new ObjectParameter("CaseID", typeof(string));
    
            var sourceIDParameter = sourceID.HasValue ?
                new ObjectParameter("SourceID", sourceID) :
                new ObjectParameter("SourceID", typeof(int));
    
            var receivedSourceIDParameter = receivedSourceID.HasValue ?
                new ObjectParameter("ReceivedSourceID", receivedSourceID) :
                new ObjectParameter("ReceivedSourceID", typeof(int));
    
            var mobileOperatorIDParameter = mobileOperatorID.HasValue ?
                new ObjectParameter("MobileOperatorID", mobileOperatorID) :
                new ObjectParameter("MobileOperatorID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var priorityIDParameter = priorityID.HasValue ?
                new ObjectParameter("PriorityID", priorityID) :
                new ObjectParameter("PriorityID", typeof(int));
    
            var reportingStatusIDParameter = reportingStatusID.HasValue ?
                new ObjectParameter("ReportingStatusID", reportingStatusID) :
                new ObjectParameter("ReportingStatusID", typeof(int));
    
            var a_numberParameter = a_number != null ?
                new ObjectParameter("a_number", a_number) :
                new ObjectParameter("a_number", typeof(string));
    
            var b_numberParameter = b_number != null ?
                new ObjectParameter("b_number", b_number) :
                new ObjectParameter("b_number", typeof(string));
    
            var cLIParameter = cLI != null ?
                new ObjectParameter("CLI", cLI) :
                new ObjectParameter("CLI", typeof(string));
    
            var originationNetworkParameter = originationNetwork != null ?
                new ObjectParameter("OriginationNetwork", originationNetwork) :
                new ObjectParameter("OriginationNetwork", typeof(string));
    
            var fromAttemptDateTimeParameter = fromAttemptDateTime.HasValue ?
                new ObjectParameter("FromAttemptDateTime", fromAttemptDateTime) :
                new ObjectParameter("FromAttemptDateTime", typeof(System.DateTime));
    
            var toAttemptDateTimeParameter = toAttemptDateTime.HasValue ?
                new ObjectParameter("ToAttemptDateTime", toAttemptDateTime) :
                new ObjectParameter("ToAttemptDateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prResultingCases_Result>("prResultingCases", caseIDParameter, sourceIDParameter, receivedSourceIDParameter, mobileOperatorIDParameter, statusIDParameter, priorityIDParameter, reportingStatusIDParameter, a_numberParameter, b_numberParameter, cLIParameter, originationNetworkParameter, fromAttemptDateTimeParameter, toAttemptDateTimeParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prVwGeneratedCall_Result> prVwGeneratedCall(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prVwGeneratedCall_Result>("prVwGeneratedCall", iDParameter);
        }
    
        public virtual ObjectResult<prGetReportedCalls_Result> prGetReportedCalls(string caseID, string b_number, string cLI, Nullable<System.DateTime> fromSentDateTime, Nullable<System.DateTime> toSentDateTime, string reportID, Nullable<int> cLIMobileOperatorID, Nullable<int> b_NumberMobileOperatorID, Nullable<int> mobileOperatorFeedbackID, Nullable<int> recommendedActionID, Nullable<int> clientID)
        {
            var caseIDParameter = caseID != null ?
                new ObjectParameter("CaseID", caseID) :
                new ObjectParameter("CaseID", typeof(string));
    
            var b_numberParameter = b_number != null ?
                new ObjectParameter("b_number", b_number) :
                new ObjectParameter("b_number", typeof(string));
    
            var cLIParameter = cLI != null ?
                new ObjectParameter("CLI", cLI) :
                new ObjectParameter("CLI", typeof(string));
    
            var fromSentDateTimeParameter = fromSentDateTime.HasValue ?
                new ObjectParameter("FromSentDateTime", fromSentDateTime) :
                new ObjectParameter("FromSentDateTime", typeof(System.DateTime));
    
            var toSentDateTimeParameter = toSentDateTime.HasValue ?
                new ObjectParameter("ToSentDateTime", toSentDateTime) :
                new ObjectParameter("ToSentDateTime", typeof(System.DateTime));
    
            var reportIDParameter = reportID != null ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(string));
    
            var cLIMobileOperatorIDParameter = cLIMobileOperatorID.HasValue ?
                new ObjectParameter("CLIMobileOperatorID", cLIMobileOperatorID) :
                new ObjectParameter("CLIMobileOperatorID", typeof(int));
    
            var b_NumberMobileOperatorIDParameter = b_NumberMobileOperatorID.HasValue ?
                new ObjectParameter("B_NumberMobileOperatorID", b_NumberMobileOperatorID) :
                new ObjectParameter("B_NumberMobileOperatorID", typeof(int));
    
            var mobileOperatorFeedbackIDParameter = mobileOperatorFeedbackID.HasValue ?
                new ObjectParameter("MobileOperatorFeedbackID", mobileOperatorFeedbackID) :
                new ObjectParameter("MobileOperatorFeedbackID", typeof(int));
    
            var recommendedActionIDParameter = recommendedActionID.HasValue ?
                new ObjectParameter("RecommendedActionID", recommendedActionID) :
                new ObjectParameter("RecommendedActionID", typeof(int));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetReportedCalls_Result>("prGetReportedCalls", caseIDParameter, b_numberParameter, cLIParameter, fromSentDateTimeParameter, toSentDateTimeParameter, reportIDParameter, cLIMobileOperatorIDParameter, b_NumberMobileOperatorIDParameter, mobileOperatorFeedbackIDParameter, recommendedActionIDParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prGetReportedCalls_1_Result> prGetReportedCalls_1(string caseID, string b_number, string cLI, Nullable<System.DateTime> fromSentDateTime, Nullable<System.DateTime> toSentDateTime, string reportID, Nullable<int> cLIMobileOperatorID, Nullable<int> b_NumberMobileOperatorID, Nullable<int> mobileOperatorFeedbackID, Nullable<int> recommendedActionID, Nullable<int> clientID)
        {
            var caseIDParameter = caseID != null ?
                new ObjectParameter("CaseID", caseID) :
                new ObjectParameter("CaseID", typeof(string));
    
            var b_numberParameter = b_number != null ?
                new ObjectParameter("b_number", b_number) :
                new ObjectParameter("b_number", typeof(string));
    
            var cLIParameter = cLI != null ?
                new ObjectParameter("CLI", cLI) :
                new ObjectParameter("CLI", typeof(string));
    
            var fromSentDateTimeParameter = fromSentDateTime.HasValue ?
                new ObjectParameter("FromSentDateTime", fromSentDateTime) :
                new ObjectParameter("FromSentDateTime", typeof(System.DateTime));
    
            var toSentDateTimeParameter = toSentDateTime.HasValue ?
                new ObjectParameter("ToSentDateTime", toSentDateTime) :
                new ObjectParameter("ToSentDateTime", typeof(System.DateTime));
    
            var reportIDParameter = reportID != null ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(string));
    
            var cLIMobileOperatorIDParameter = cLIMobileOperatorID.HasValue ?
                new ObjectParameter("CLIMobileOperatorID", cLIMobileOperatorID) :
                new ObjectParameter("CLIMobileOperatorID", typeof(int));
    
            var b_NumberMobileOperatorIDParameter = b_NumberMobileOperatorID.HasValue ?
                new ObjectParameter("B_NumberMobileOperatorID", b_NumberMobileOperatorID) :
                new ObjectParameter("B_NumberMobileOperatorID", typeof(int));
    
            var mobileOperatorFeedbackIDParameter = mobileOperatorFeedbackID.HasValue ?
                new ObjectParameter("MobileOperatorFeedbackID", mobileOperatorFeedbackID) :
                new ObjectParameter("MobileOperatorFeedbackID", typeof(int));
    
            var recommendedActionIDParameter = recommendedActionID.HasValue ?
                new ObjectParameter("RecommendedActionID", recommendedActionID) :
                new ObjectParameter("RecommendedActionID", typeof(int));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetReportedCalls_1_Result>("prGetReportedCalls_1", caseIDParameter, b_numberParameter, cLIParameter, fromSentDateTimeParameter, toSentDateTimeParameter, reportIDParameter, cLIMobileOperatorIDParameter, b_NumberMobileOperatorIDParameter, mobileOperatorFeedbackIDParameter, recommendedActionIDParameter, clientIDParameter);
        }
    
        public virtual ObjectResult<prGetReportedCalls_old_Result> prGetReportedCalls_old(string caseID, string b_number, string cLI, Nullable<System.DateTime> fromSentDateTime, Nullable<System.DateTime> toSentDateTime, string reportID, Nullable<int> cLIMobileOperatorID, Nullable<int> b_NumberMobileOperatorID, Nullable<int> mobileOperatorFeedbackID, Nullable<int> recommendedActionID, Nullable<int> clientID)
        {
            var caseIDParameter = caseID != null ?
                new ObjectParameter("CaseID", caseID) :
                new ObjectParameter("CaseID", typeof(string));
    
            var b_numberParameter = b_number != null ?
                new ObjectParameter("b_number", b_number) :
                new ObjectParameter("b_number", typeof(string));
    
            var cLIParameter = cLI != null ?
                new ObjectParameter("CLI", cLI) :
                new ObjectParameter("CLI", typeof(string));
    
            var fromSentDateTimeParameter = fromSentDateTime.HasValue ?
                new ObjectParameter("FromSentDateTime", fromSentDateTime) :
                new ObjectParameter("FromSentDateTime", typeof(System.DateTime));
    
            var toSentDateTimeParameter = toSentDateTime.HasValue ?
                new ObjectParameter("ToSentDateTime", toSentDateTime) :
                new ObjectParameter("ToSentDateTime", typeof(System.DateTime));
    
            var reportIDParameter = reportID != null ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(string));
    
            var cLIMobileOperatorIDParameter = cLIMobileOperatorID.HasValue ?
                new ObjectParameter("CLIMobileOperatorID", cLIMobileOperatorID) :
                new ObjectParameter("CLIMobileOperatorID", typeof(int));
    
            var b_NumberMobileOperatorIDParameter = b_NumberMobileOperatorID.HasValue ?
                new ObjectParameter("B_NumberMobileOperatorID", b_NumberMobileOperatorID) :
                new ObjectParameter("B_NumberMobileOperatorID", typeof(int));
    
            var mobileOperatorFeedbackIDParameter = mobileOperatorFeedbackID.HasValue ?
                new ObjectParameter("MobileOperatorFeedbackID", mobileOperatorFeedbackID) :
                new ObjectParameter("MobileOperatorFeedbackID", typeof(int));
    
            var recommendedActionIDParameter = recommendedActionID.HasValue ?
                new ObjectParameter("RecommendedActionID", recommendedActionID) :
                new ObjectParameter("RecommendedActionID", typeof(int));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prGetReportedCalls_old_Result>("prGetReportedCalls_old", caseIDParameter, b_numberParameter, cLIParameter, fromSentDateTimeParameter, toSentDateTimeParameter, reportIDParameter, cLIMobileOperatorIDParameter, b_NumberMobileOperatorIDParameter, mobileOperatorFeedbackIDParameter, recommendedActionIDParameter, clientIDParameter);
        }
    
        [EdmFunction("Entities", "Split")]
        public virtual IQueryable<string> Split(string input)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[Entities].[Split](@input)", inputParameter);
        }
    
        [EdmFunction("Entities", "SplitwithValue")]
        public virtual IQueryable<SplitwithValue_Result> SplitwithValue(string input, Nullable<int> extraValue)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            var extraValueParameter = extraValue.HasValue ?
                new ObjectParameter("ExtraValue", extraValue) :
                new ObjectParameter("ExtraValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitwithValue_Result>("[Entities].[SplitwithValue](@input, @ExtraValue)", inputParameter, extraValueParameter);
        }
    }
}
