//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedColumnsforRelatedNumber
    {
        public PredefinedColumnsforRelatedNumber()
        {
            this.RelatedNumberMappings = new HashSet<RelatedNumberMapping>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RelatedNumberMapping> RelatedNumberMappings { get; set; }
    }
}
