//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedNumberMapping
    {
        public int ID { get; set; }
        public int MobileOperatorID { get; set; }
        public string ColumnName { get; set; }
        public int MappedtoColumnNumber { get; set; }
    
        public virtual MobileOperator MobileOperator { get; set; }
        public virtual PredefinedColumnsforRelatedNumber PredefinedColumnsforRelatedNumber { get; set; }
        public virtual Source Source { get; set; }
    }
}
