//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.RecievedCalls = new HashSet<RecievedCall>();
            this.RelatedNumberMappings = new HashSet<RelatedNumberMapping>();
            this.SourceMappings = new HashSet<SourceMapping>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int GMT { get; set; }
        public string Email { get; set; }
        public Nullable<int> SourceTypeID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> SourceKindID { get; set; }
    
        public virtual ICollection<RecievedCall> RecievedCalls { get; set; }
        public virtual ICollection<RelatedNumberMapping> RelatedNumberMappings { get; set; }
        public virtual SourceKind SourceKind { get; set; }
        public virtual ICollection<SourceMapping> SourceMappings { get; set; }
        public virtual SourceType SourceType { get; set; }
    }
}
