//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ApplicationUsers = new HashSet<ApplicationUser>();
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.LoggedActions = new HashSet<LoggedAction>();
            this.MobileOperators = new HashSet<MobileOperator>();
            this.SysParameters = new HashSet<SysParameter>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserPermissions1 = new HashSet<UserPermission>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsSuperUser { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<int> AppTypeID { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public int MaxDailyCases { get; set; }
        public string Mobile { get; set; }
        public string Prefix { get; set; }
        public string ContactName { get; set; }
        public string Website { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int GMT { get; set; }
    
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<LoggedAction> LoggedActions { get; set; }
        public virtual ICollection<MobileOperator> MobileOperators { get; set; }
        public virtual ICollection<SysParameter> SysParameters { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<UserPermission> UserPermissions1 { get; set; }
        public virtual Client Client { get; set; }
    }
}
