//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Origination
    {
        public string OriginationNetwork { get; set; }
        public Nullable<int> MobileOperatorID { get; set; }
        public System.DateTime AttemptDateTime { get; set; }
        public Nullable<int> count { get; set; }
    }
}
