//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFraudCase
    {
        public int Occurance { get; set; }
        public string CaseID { get; set; }
        public string OriginationNetwork { get; set; }
        public string Carrier { get; set; }
        public System.DateTime LastAttemptDateTime { get; set; }
        public System.DateTime FirstAttemptDateTime { get; set; }
        public string b_number { get; set; }
        public string CLI { get; set; }
        public int ID { get; set; }
        public int MobileOperatorID { get; set; }
    }
}
