//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.Bypass
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteMenu
    {
        public WebsiteMenu()
        {
            this.WebsiteMenus1 = new HashSet<WebsiteMenu>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AppType { get; set; }
        public Nullable<int> MainMenuID { get; set; }
        public int Ordering { get; set; }
        public Nullable<int> PermissionID { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual ICollection<WebsiteMenu> WebsiteMenus1 { get; set; }
        public virtual WebsiteMenu WebsiteMenu1 { get; set; }
    }
}
