//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.CDRAnalysis.Mobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public int ID { get; set; }
        public System.DateTime ImportDate { get; set; }
        public Nullable<int> ImportedBy { get; set; }
        public int ImportTypeId { get; set; }
    
        public virtual ImportType ImportType { get; set; }
        public virtual User User { get; set; }
    }
}
