//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.CDRAnalysis.Mobile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CDR> CDRs { get; set; }
        public DbSet<ControlTable> ControlTables { get; set; }
        public DbSet<Criteria_Profile> Criteria_Profile { get; set; }
        public DbSet<Direction> Directions { get; set; }
        public DbSet<EmailReceiver> EmailReceivers { get; set; }
        public DbSet<EmailReceiverType> EmailReceiverTypes { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<EmailToken> EmailTokens { get; set; }
        public DbSet<Import> Imports { get; set; }
        public DbSet<ImportType> ImportTypes { get; set; }
        public DbSet<MobileCDR> MobileCDRs { get; set; }
        public DbSet<NormalCDR> NormalCDRs { get; set; }
        public DbSet<NormalizationRule> NormalizationRules { get; set; }
        public DbSet<NumberProfile> NumberProfiles { get; set; }
        public DbSet<OperationType> OperationTypes { get; set; }
        public DbSet<Peak_Hoursold> Peak_Hoursold { get; set; }
        public DbSet<Peak_Time> Peak_Time { get; set; }
        public DbSet<Period> Periods { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<PredefinedColumn> PredefinedColumns { get; set; }
        public DbSet<Related_Criteria> Related_Criteria { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<ReportDetail> ReportDetails { get; set; }
        public DbSet<ReportingStatu> ReportingStatus { get; set; }
        public DbSet<SourceMapping> SourceMappings { get; set; }
        public DbSet<Strategy> Strategies { get; set; }
        public DbSet<Strategy_Min_Values> Strategy_Min_Values { get; set; }
        public DbSet<Strategy_Suspection_Level> Strategy_Suspection_Level { get; set; }
        public DbSet<StrategyPeriod> StrategyPeriods { get; set; }
        public DbSet<StrategyThreshold> StrategyThresholds { get; set; }
        public DbSet<Subscriber_Values> Subscriber_Values { get; set; }
        public DbSet<SubscriberThreshold> SubscriberThresholds { get; set; }
        public DbSet<Suspection_Level> Suspection_Level { get; set; }
        public DbSet<Switch_DatabaseConnections> Switch_DatabaseConnections { get; set; }
        public DbSet<SwitchProfile> SwitchProfiles { get; set; }
        public DbSet<SwitchTrunck> SwitchTruncks { get; set; }
        public DbSet<SwitchTruncksold> SwitchTruncksolds { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Trunck> Truncks { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<AN_Profiling> AN_Profiling { get; set; }
        public DbSet<NormalizationRulesBackup> NormalizationRulesBackups { get; set; }
        public DbSet<profiletest> profiletests { get; set; }
        public DbSet<vw_Dashboard> vw_Dashboard { get; set; }
        public DbSet<vw_ReportedNumber> vw_ReportedNumber { get; set; }
        public DbSet<vw_ReportedNumberNormalCDR> vw_ReportedNumberNormalCDR { get; set; }
        public DbSet<vwSuspectionAnalysi> vwSuspectionAnalysis { get; set; }
    }
}
