//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanrise.Fzero.CDRAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReportedNumberNormalCDR
    {
        public int Id { get; set; }
        public string A_Temp { get; set; }
        public string In_Trunk { get; set; }
        public string Switch { get; set; }
        public int ReportID { get; set; }
    }
}
