//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace PhoneNumberServiceApp.PhoneNumberWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PhoneNumberServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PhoneNumberService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestForCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReleaseCallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhoneNumberService() {
            this.Url = global::PhoneNumberServiceApp.Properties.Settings.Default.PhoneNumberServiceApp_PhoneNumberWebReference_PhoneNumberService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestForCallCompletedEventHandler RequestForCallCompleted;
        
        /// <remarks/>
        public event ReleaseCallCompletedEventHandler ReleaseCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RequestForCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneNumberReturn RequestForCall(string clientName, string password, string mcc, string mnc) {
            object[] results = this.Invoke("RequestForCall", new object[] {
                        clientName,
                        password,
                        mcc,
                        mnc});
            return ((PhoneNumberReturn)(results[0]));
        }
        
        /// <remarks/>
        public void RequestForCallAsync(string clientName, string password, string mcc, string mnc) {
            this.RequestForCallAsync(clientName, password, mcc, mnc, null);
        }
        
        /// <remarks/>
        public void RequestForCallAsync(string clientName, string password, string mcc, string mnc, object userState) {
            if ((this.RequestForCallOperationCompleted == null)) {
                this.RequestForCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestForCallOperationCompleted);
            }
            this.InvokeAsync("RequestForCall", new object[] {
                        clientName,
                        password,
                        mcc,
                        mnc}, this.RequestForCallOperationCompleted, userState);
        }
        
        private void OnRequestForCallOperationCompleted(object arg) {
            if ((this.RequestForCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestForCallCompleted(this, new RequestForCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReleaseCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CallInfo ReleaseCall(string clientName, string password, int requestId) {
            object[] results = this.Invoke("ReleaseCall", new object[] {
                        clientName,
                        password,
                        requestId});
            return ((CallInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ReleaseCallAsync(string clientName, string password, int requestId) {
            this.ReleaseCallAsync(clientName, password, requestId, null);
        }
        
        /// <remarks/>
        public void ReleaseCallAsync(string clientName, string password, int requestId, object userState) {
            if ((this.ReleaseCallOperationCompleted == null)) {
                this.ReleaseCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReleaseCallOperationCompleted);
            }
            this.InvokeAsync("ReleaseCall", new object[] {
                        clientName,
                        password,
                        requestId}, this.ReleaseCallOperationCompleted, userState);
        }
        
        private void OnReleaseCallOperationCompleted(object arg) {
            if ((this.ReleaseCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReleaseCallCompleted(this, new ReleaseCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhoneNumberReturn {
        
        private int requestCallIdField;
        
        private string numberField;
        
        private string prefixField;
        
        private string statusField;
        
        /// <remarks/>
        public int RequestCallId {
            get {
                return this.requestCallIdField;
            }
            set {
                this.requestCallIdField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CallInfo {
        
        private int requestCallIdField;
        
        private string receivedCLIField;
        
        /// <remarks/>
        public int RequestCallId {
            get {
                return this.requestCallIdField;
            }
            set {
                this.requestCallIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReceivedCLI {
            get {
                return this.receivedCLIField;
            }
            set {
                this.receivedCLIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RequestForCallCompletedEventHandler(object sender, RequestForCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestForCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestForCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PhoneNumberReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PhoneNumberReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ReleaseCallCompletedEventHandler(object sender, ReleaseCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReleaseCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReleaseCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CallInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CallInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591