//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineOperatorsTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.clireporterSoap")]
    public interface clireporterSoap {
        
        // CODEGEN: Generating message contract since message GetMMCandMNCRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMCandMNC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OnlineOperatorsTest.ServiceReference1.GetMMCandMNCResponse GetMMCandMNC(OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMCandMNC", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.GetMMCandMNCResponse> GetMMCandMNCAsync(OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest request);
        
        // CODEGEN: Generating message contract since message GetCLIRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCLI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OnlineOperatorsTest.ServiceReference1.GetCLIResponse GetCLI(OnlineOperatorsTest.ServiceReference1.GetCLIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCLI", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.GetCLIResponse> GetCLIAsync(OnlineOperatorsTest.ServiceReference1.GetCLIRequest request);
        
        // CODEGEN: Generating message contract since message RequestForCallRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestForCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OnlineOperatorsTest.ServiceReference1.RequestForCallResponse RequestForCall(OnlineOperatorsTest.ServiceReference1.RequestForCallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestForCall", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.RequestForCallResponse> RequestForCallAsync(OnlineOperatorsTest.ServiceReference1.RequestForCallRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NumberID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileNumberField;
        
        private string callidField;
        
        private string errorStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("mobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Callid {
            get {
                return this.callidField;
            }
            set {
                this.callidField = value;
                this.RaisePropertyChanged("Callid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorStatus {
            get {
                return this.errorStatusField;
            }
            set {
                this.errorStatusField = value;
                this.RaisePropertyChanged("ErrorStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Call : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string callIDField;
        
        private string cLIField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        private string countryField;
        
        private string carrierField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string callID {
            get {
                return this.callIDField;
            }
            set {
                this.callIDField = value;
                this.RaisePropertyChanged("callID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CLI {
            get {
                return this.cLIField;
            }
            set {
                this.cLIField = value;
                this.RaisePropertyChanged("CLI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
                this.RaisePropertyChanged("carrier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CountryCarrier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string carrierField;
        
        private string mccField;
        
        private string mncField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
                this.RaisePropertyChanged("carrier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mcc {
            get {
                return this.mccField;
            }
            set {
                this.mccField = value;
                this.RaisePropertyChanged("mcc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mnc {
            get {
                return this.mncField;
            }
            set {
                this.mncField = value;
                this.RaisePropertyChanged("mnc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMMCandMNC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMMCandMNCRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        public GetMMCandMNCRequest() {
        }
        
        public GetMMCandMNCRequest(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password) {
            this.ServiceAuthHeader = ServiceAuthHeader;
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMMCandMNCResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMMCandMNCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineOperatorsTest.ServiceReference1.CountryCarrier[] GetMMCandMNCResult;
        
        public GetMMCandMNCResponse() {
        }
        
        public GetMMCandMNCResponse(OnlineOperatorsTest.ServiceReference1.CountryCarrier[] GetMMCandMNCResult) {
            this.GetMMCandMNCResult = GetMMCandMNCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCLI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCLIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CallID;
        
        public GetCLIRequest() {
        }
        
        public GetCLIRequest(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password, string CallID) {
            this.ServiceAuthHeader = ServiceAuthHeader;
            this.Username = Username;
            this.Password = Password;
            this.CallID = CallID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCLIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCLIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineOperatorsTest.ServiceReference1.Call GetCLIResult;
        
        public GetCLIResponse() {
        }
        
        public GetCLIResponse(OnlineOperatorsTest.ServiceReference1.Call GetCLIResult) {
            this.GetCLIResult = GetCLIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestForCall", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestForCallRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string MNC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string DateTimeC;
        
        public RequestForCallRequest() {
        }
        
        public RequestForCallRequest(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password, string MCC, string MNC, string DateTimeC) {
            this.ServiceAuthHeader = ServiceAuthHeader;
            this.Username = Username;
            this.Password = Password;
            this.MCC = MCC;
            this.MNC = MNC;
            this.DateTimeC = DateTimeC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestForCallResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestForCallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineOperatorsTest.ServiceReference1.NumberID RequestForCallResult;
        
        public RequestForCallResponse() {
        }
        
        public RequestForCallResponse(OnlineOperatorsTest.ServiceReference1.NumberID RequestForCallResult) {
            this.RequestForCallResult = RequestForCallResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clireporterSoapChannel : OnlineOperatorsTest.ServiceReference1.clireporterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clireporterSoapClient : System.ServiceModel.ClientBase<OnlineOperatorsTest.ServiceReference1.clireporterSoap>, OnlineOperatorsTest.ServiceReference1.clireporterSoap {
        
        public clireporterSoapClient() {
        }
        
        public clireporterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clireporterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clireporterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clireporterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineOperatorsTest.ServiceReference1.GetMMCandMNCResponse OnlineOperatorsTest.ServiceReference1.clireporterSoap.GetMMCandMNC(OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest request) {
            return base.Channel.GetMMCandMNC(request);
        }
        
        public OnlineOperatorsTest.ServiceReference1.CountryCarrier[] GetMMCandMNC(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password) {
            OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest inValue = new OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest();
            inValue.ServiceAuthHeader = ServiceAuthHeader;
            inValue.Username = Username;
            inValue.Password = Password;
            OnlineOperatorsTest.ServiceReference1.GetMMCandMNCResponse retVal = ((OnlineOperatorsTest.ServiceReference1.clireporterSoap)(this)).GetMMCandMNC(inValue);
            return retVal.GetMMCandMNCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.GetMMCandMNCResponse> OnlineOperatorsTest.ServiceReference1.clireporterSoap.GetMMCandMNCAsync(OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest request) {
            return base.Channel.GetMMCandMNCAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.GetMMCandMNCResponse> GetMMCandMNCAsync(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password) {
            OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest inValue = new OnlineOperatorsTest.ServiceReference1.GetMMCandMNCRequest();
            inValue.ServiceAuthHeader = ServiceAuthHeader;
            inValue.Username = Username;
            inValue.Password = Password;
            return ((OnlineOperatorsTest.ServiceReference1.clireporterSoap)(this)).GetMMCandMNCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineOperatorsTest.ServiceReference1.GetCLIResponse OnlineOperatorsTest.ServiceReference1.clireporterSoap.GetCLI(OnlineOperatorsTest.ServiceReference1.GetCLIRequest request) {
            return base.Channel.GetCLI(request);
        }
        
        public OnlineOperatorsTest.ServiceReference1.Call GetCLI(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password, string CallID) {
            OnlineOperatorsTest.ServiceReference1.GetCLIRequest inValue = new OnlineOperatorsTest.ServiceReference1.GetCLIRequest();
            inValue.ServiceAuthHeader = ServiceAuthHeader;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.CallID = CallID;
            OnlineOperatorsTest.ServiceReference1.GetCLIResponse retVal = ((OnlineOperatorsTest.ServiceReference1.clireporterSoap)(this)).GetCLI(inValue);
            return retVal.GetCLIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.GetCLIResponse> OnlineOperatorsTest.ServiceReference1.clireporterSoap.GetCLIAsync(OnlineOperatorsTest.ServiceReference1.GetCLIRequest request) {
            return base.Channel.GetCLIAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.GetCLIResponse> GetCLIAsync(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password, string CallID) {
            OnlineOperatorsTest.ServiceReference1.GetCLIRequest inValue = new OnlineOperatorsTest.ServiceReference1.GetCLIRequest();
            inValue.ServiceAuthHeader = ServiceAuthHeader;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.CallID = CallID;
            return ((OnlineOperatorsTest.ServiceReference1.clireporterSoap)(this)).GetCLIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineOperatorsTest.ServiceReference1.RequestForCallResponse OnlineOperatorsTest.ServiceReference1.clireporterSoap.RequestForCall(OnlineOperatorsTest.ServiceReference1.RequestForCallRequest request) {
            return base.Channel.RequestForCall(request);
        }
        
        public OnlineOperatorsTest.ServiceReference1.NumberID RequestForCall(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password, string MCC, string MNC, string DateTimeC) {
            OnlineOperatorsTest.ServiceReference1.RequestForCallRequest inValue = new OnlineOperatorsTest.ServiceReference1.RequestForCallRequest();
            inValue.ServiceAuthHeader = ServiceAuthHeader;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.MCC = MCC;
            inValue.MNC = MNC;
            inValue.DateTimeC = DateTimeC;
            OnlineOperatorsTest.ServiceReference1.RequestForCallResponse retVal = ((OnlineOperatorsTest.ServiceReference1.clireporterSoap)(this)).RequestForCall(inValue);
            return retVal.RequestForCallResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.RequestForCallResponse> OnlineOperatorsTest.ServiceReference1.clireporterSoap.RequestForCallAsync(OnlineOperatorsTest.ServiceReference1.RequestForCallRequest request) {
            return base.Channel.RequestForCallAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineOperatorsTest.ServiceReference1.RequestForCallResponse> RequestForCallAsync(OnlineOperatorsTest.ServiceReference1.ServiceAuthHeader ServiceAuthHeader, string Username, string Password, string MCC, string MNC, string DateTimeC) {
            OnlineOperatorsTest.ServiceReference1.RequestForCallRequest inValue = new OnlineOperatorsTest.ServiceReference1.RequestForCallRequest();
            inValue.ServiceAuthHeader = ServiceAuthHeader;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.MCC = MCC;
            inValue.MNC = MNC;
            inValue.DateTimeC = DateTimeC;
            return ((OnlineOperatorsTest.ServiceReference1.clireporterSoap)(this)).RequestForCallAsync(inValue);
        }
    }
}
