//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallServiceClient.WebService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestMethodInput", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TestMethodInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestMethodOutput", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TestMethodOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Text1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Text2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text1 {
            get {
                return this.Text1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Text1Field, value) != true)) {
                    this.Text1Field = value;
                    this.RaisePropertyChanged("Text1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text2 {
            get {
                return this.Text2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Text2Field, value) != true)) {
                    this.Text2Field = value;
                    this.RaisePropertyChanged("Text2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CallServiceClient.WebService1.HelloWorldResponse HelloWorld(CallServiceClient.WebService1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CallServiceClient.WebService1.HelloWorldResponse> HelloWorldAsync(CallServiceClient.WebService1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMethod2", ReplyAction="*")]
        CallServiceClient.WebService1.TestMethod2Response TestMethod2(CallServiceClient.WebService1.TestMethod2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestMethod2", ReplyAction="*")]
        System.Threading.Tasks.Task<CallServiceClient.WebService1.TestMethod2Response> TestMethod2Async(CallServiceClient.WebService1.TestMethod2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CallServiceClient.WebService1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CallServiceClient.WebService1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CallServiceClient.WebService1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CallServiceClient.WebService1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethod2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethod2", Namespace="http://tempuri.org/", Order=0)]
        public CallServiceClient.WebService1.TestMethod2RequestBody Body;
        
        public TestMethod2Request() {
        }
        
        public TestMethod2Request(CallServiceClient.WebService1.TestMethod2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestMethod2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CallServiceClient.WebService1.TestMethodInput input;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CallServiceClient.WebService1.TestMethodInput input2;
        
        public TestMethod2RequestBody() {
        }
        
        public TestMethod2RequestBody(CallServiceClient.WebService1.TestMethodInput input, CallServiceClient.WebService1.TestMethodInput input2) {
            this.input = input;
            this.input2 = input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMethod2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMethod2Response", Namespace="http://tempuri.org/", Order=0)]
        public CallServiceClient.WebService1.TestMethod2ResponseBody Body;
        
        public TestMethod2Response() {
        }
        
        public TestMethod2Response(CallServiceClient.WebService1.TestMethod2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestMethod2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CallServiceClient.WebService1.TestMethodOutput TestMethod2Result;
        
        public TestMethod2ResponseBody() {
        }
        
        public TestMethod2ResponseBody(CallServiceClient.WebService1.TestMethodOutput TestMethod2Result) {
            this.TestMethod2Result = TestMethod2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CallServiceClient.WebService1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CallServiceClient.WebService1.WebService1Soap>, CallServiceClient.WebService1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallServiceClient.WebService1.HelloWorldResponse CallServiceClient.WebService1.WebService1Soap.HelloWorld(CallServiceClient.WebService1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CallServiceClient.WebService1.HelloWorldRequest inValue = new CallServiceClient.WebService1.HelloWorldRequest();
            inValue.Body = new CallServiceClient.WebService1.HelloWorldRequestBody();
            CallServiceClient.WebService1.HelloWorldResponse retVal = ((CallServiceClient.WebService1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallServiceClient.WebService1.HelloWorldResponse> CallServiceClient.WebService1.WebService1Soap.HelloWorldAsync(CallServiceClient.WebService1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallServiceClient.WebService1.HelloWorldResponse> HelloWorldAsync() {
            CallServiceClient.WebService1.HelloWorldRequest inValue = new CallServiceClient.WebService1.HelloWorldRequest();
            inValue.Body = new CallServiceClient.WebService1.HelloWorldRequestBody();
            return ((CallServiceClient.WebService1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallServiceClient.WebService1.TestMethod2Response CallServiceClient.WebService1.WebService1Soap.TestMethod2(CallServiceClient.WebService1.TestMethod2Request request) {
            return base.Channel.TestMethod2(request);
        }
        
        public CallServiceClient.WebService1.TestMethodOutput TestMethod2(CallServiceClient.WebService1.TestMethodInput input, CallServiceClient.WebService1.TestMethodInput input2) {
            CallServiceClient.WebService1.TestMethod2Request inValue = new CallServiceClient.WebService1.TestMethod2Request();
            inValue.Body = new CallServiceClient.WebService1.TestMethod2RequestBody();
            inValue.Body.input = input;
            inValue.Body.input2 = input2;
            CallServiceClient.WebService1.TestMethod2Response retVal = ((CallServiceClient.WebService1.WebService1Soap)(this)).TestMethod2(inValue);
            return retVal.Body.TestMethod2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallServiceClient.WebService1.TestMethod2Response> CallServiceClient.WebService1.WebService1Soap.TestMethod2Async(CallServiceClient.WebService1.TestMethod2Request request) {
            return base.Channel.TestMethod2Async(request);
        }
        
        public System.Threading.Tasks.Task<CallServiceClient.WebService1.TestMethod2Response> TestMethod2Async(CallServiceClient.WebService1.TestMethodInput input, CallServiceClient.WebService1.TestMethodInput input2) {
            CallServiceClient.WebService1.TestMethod2Request inValue = new CallServiceClient.WebService1.TestMethod2Request();
            inValue.Body = new CallServiceClient.WebService1.TestMethod2RequestBody();
            inValue.Body.input = input;
            inValue.Body.input2 = input2;
            return ((CallServiceClient.WebService1.WebService1Soap)(this)).TestMethod2Async(inValue);
        }
    }
}
